### ISSUE TITLE
🐛 Bug Report: 

### ISSUE THREAD

**Issue by franx82** [stonith404/pingvin-share#121]
### 👟 Reproduction steps

When I try to create a new user and SMTP is enabled 

### 👍 Expected behavior

It should create a new user

### 👎 Actual Behavior

I actually get the following error:
```
[Nest] 210  - 03/08/2023, 11:46:05 AM   ERROR [ExceptionsHandler] crypto is not defined
ReferenceError: crypto is not defined
    at UserSevice.create (/opt/app/backend/dist/src/user/user.service.js:32:36)
    at UserController.create (/opt/app/backend/dist/src/user/user.controller.js:49:69)
    at /opt/app/backend/node_modules/@nestjs/core/router/router-execution-context.js:38:29

```

### 🌐 Browser

Edge

**Comment by stonith404** [comment]
Thanks for your report! This issue could occur on some environments, I've fixed it in 8f71fd343506506532c1a24a4c66a16b1021705f and I'll release it ASAP.

**Comment by stonith404** [comment]
fixed in `v0.12.0`
