### ISSUE TITLE
🐛 Bug Report: 

### ISSUE THREAD

**Issue by Trilis29** [stonith404/pingvin-share#271]
### 👟 Reproduction steps

Docker instalation got error:

`[Nest] 33  - 09/27/2023, 5:33:18 PM     LOG [RouterExplorer] Mapped {/api/users/:id, DELETE} route +0ms
    at Function.supportedLocalesOf (<anonymous>)
RangeError: Incorrect locale information provided
    at new IntlProvider (/opt/app/frontend/node_modules/react-intl/src/components/provider.js:92:42)
    at Zc (/opt/app/frontend/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:70:481)
    at Z (/opt/app/frontend/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:76:89)
    at Zc (/opt/app/frontend/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:70:141)
    at createIntl (/opt/app/frontend/node_modules/react-intl/src/components/provider.js:66:42)
    at createIntl (/opt/app/frontend/node_modules/@formatjs/intl/src/create-intl.js:45:33)`

### 👍 Expected behavior

Work

### 👎 Actual Behavior

Not opening web "Internal server error"

### 🌐 Browser

Chrome

**Comment by stonith404** [comment]
Do you run Pingvin Share in Docker? And which is your system locale on the client machine (e.g `EN-US`)?

**Comment by stonith404** [comment]
Closing this due to inactivity. Feel free to reopen it if the issue still persists.

**Comment by nilsherzig** [comment]
Hi, i have the same issue while using firefox (works in chrome). Running the latest container inside kubernetes.

Client locale:

```bash
> locale
LANG=en_US.UTF-8
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC=de_DE.UTF-8
LC_TIME=de_DE.UTF-8
LC_COLLATE="en_US.UTF-8"
LC_MONETARY=de_DE.UTF-8
LC_MESSAGES="en_US.UTF-8"
LC_PAPER=de_DE.UTF-8
LC_NAME=de_DE.UTF-8
LC_ADDRESS=de_DE.UTF-8
LC_TELEPHONE=de_DE.UTF-8
LC_MEASUREMENT=de_DE.UTF-8
LC_IDENTIFICATION=de_DE.UTF-8
LC_ALL=
```

Browser locale:

Left is firefox, right is chrome.

![image](https://github.com/stonith404/pingvin-share/assets/72463901/23deace6-713b-45b7-b370-03cfb3b2da98)

**Comment by stonith404** [comment]
Thanks for sharing this information. Could you please share the request headers that are sent to Pingvin Share? You can find them in the developer tools like this:
![image](https://github.com/stonith404/pingvin-share/assets/58886915/3f917a61-6aed-46d8-923e-2092c84f331a)

**Comment by nilsherzig** [comment]
Sure thing :) thanks for your project. 

Running the webinterface behind [ciliums envoy proxy](https://docs.cilium.io/en/latest/security/network/proxy/envoy/) solves the problem for me. I wasnt going to run the container without an reverse proxy anyway. 

Network request when accessing the container directly (only request, besides the favicon one):

![image](https://github.com/stonith404/pingvin-share/assets/72463901/03103bb2-97de-45b5-9e14-258130fb2f12)

Exported as har:

```har
{
  "log": {
    "version": "1.2",
    "creator": {
      "name": "Firefox",
      "version": "126.0.1"
    },
    "browser": {
      "name": "Firefox",
      "version": "126.0.1"
    },
    "pages": [
      {
        "id": "page_1",
        "pageTimings": {
          "onContentLoad": 60,
          "onLoad": 63
        },
        "startedDateTime": "2024-06-12T15:43:14.720+02:00",
        "title": "http://localhost:3000/"
      }
    ],
    "entries": [
      {
        "startedDateTime": "2024-06-12T15:43:14.720+02:00",
        "request": {
          "bodySize": 0,
          "method": "GET",
          "url": "http://localhost:3000/",
          "httpVersion": "HTTP/1.1",
          "headers": [
            {
              "name": "Host",
              "value": "localhost:3000"
            },
            {
              "name": "User-Agent",
              "value": "Mozilla/5.0 (X11; Linux x86_64; rv:126.0) Gecko/20100101 Firefox/126.0"
            },
            {
              "name": "Accept",
              "value": "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,*/*;q=0.8"
            },
            {
              "name": "Accept-Language",
              "value": "en-US,en;q=0.5"
            },
            {
              "name": "Accept-Encoding",
              "value": "gzip, deflate, br, zstd"
            },
            {
              "name": "Connection",
              "value": "keep-alive"
            },
            {
              "name": "Cookie",
              "value": "categories=general; language=auto; locale=en; autocomplete=; image_proxy=1; method=POST; safesearch=0; theme=simple; results_on_new_tab=0; doi_resolver=oadoi.org; simple_style=auto; center_alignment=0; advanced_search=0; query_in_title=0; infinite_scroll=0; search_on_category_select=1; hotkeys=default; disabled_engines=; enabled_engines=; disabled_plugins=; enabled_plugins=; tokens=; maintab=on; enginetab=on; preferences=; argocd.token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJhcmdvY2QiLCJzdWIiOiJhZG1pbjpsb2dpbiIsImV4cCI6MTcxODI3NTcxMywibmJmIjoxNzE4MTg5MzEzLCJpYXQiOjE3MTgxODkzMTMsImp0aSI6IjU3MjFlOGIxLTIwNDgtNDExMi04ZTExLTAxZDhmNmEwZTY3MyJ9.rbR6ToBtsVPXYkBcqiAxEvP29HYTJL_dHKfmWV08QTA; token=eyJhbGciOiJSUzI1NiIsImtpZCI6IjNqXzAzcmxoY2ZnOEI4SHZ1NzMwZndLQkRPbnlYMmFvRXFYR0pubTFiUkUifQ.eyJhdWQiOlsiaHR0cHM6Ly8xMC4xMC4xMC4xNDI6NjQ0MyJdLCJleHAiOjE3MTgxOTQ5MjksImlhdCI6MTcxODE5MTMyOSwiaXNzIjoiaHR0cHM6Ly8xMC4xMC4xMC4xNDI6NjQ0MyIsImp0aSI6IjdkNDIxMjk1LTNkZTMtNDNiNy1hOWU2LTRlYmQ0MjVhMDg4OSIsImt1YmVybmV0ZXMuaW8iOnsibmFtZXNwYWNlIjoia3ViZXJuZXRlcy1kYXNoYm9hcmQiLCJzZXJ2aWNlYWNjb3VudCI6eyJuYW1lIjoiYWRtaW4tdXNlciIsInVpZCI6ImU0NTIwYzU0LWE2OWEtNDk5OC1iNGNmLWQ5NmUzZDU1MWRmZiJ9fSwibmJmIjoxNzE4MTkxMzI5LCJzdWIiOiJzeXN0ZW06c2VydmljZWFjY291bnQ6a3ViZXJuZXRlcy1kYXNoYm9hcmQ6YWRtaW4tdXNlciJ9.JWpeuiCv03PqVPxpJo9sO-wL8aew1qS-99ALAWt1AksLib5P4pfoxvoav81xk-04ZlNJ6BlYi3lv_uBEG0GoSHTGL_VKW2D90StsIYn3d74tUn4qbRwNtN-ur9TVWuv8dP47BOiV13Hjiki8vhy2EYe_6D0uvhsG_8grlokAdGk9DjYfn6p37ob4nnA78dXONqi4sr7I9i6soYWKSzU65cluvQj6f77iVN4xO6fEnrioIeunyt85Jz7s7OPqSX4waJXcOdi2N1G8iMSfdAXCEkhpFSdPnXGMURK1ItxAs08BRUDtqtnU7UeE7d-yY4VAudTM0IWGoTfPuHocG0oDY7s9n1CQStJUYxbRXEd8VUojVS_uY5zqw7EWpCxb3wdV_MtfBeWzK4HHdVQh8jW39jpGISSG2wnPkQM7M7mAUDZIEv-28HUouNV9MAYAlU6fKj_OAwsqIP4d3tEUK3ecphYYOZVHES38w4KyCh5Woge1SPSC9AssxbMwxdb4tfPH2Bxs29cFJS-yNGSpBbEHi9NAV-03Bzrloij3iuJ0Zc-XpBUtyE3d3dAy1ETsW-ZGc9eVUJP0CbmXU2YCulPmDvGHJMQYmcvOFYI-bUy0mfTTdcbkeVIZuX9cSXiMc22-juaQMncGDw5lLrDgkHcQEc-Ic7hVNaSDUYSZb0WtYsI"
            },
            {
              "name": "Upgrade-Insecure-Requests",
              "value": "1"
            },
            {
              "name": "Sec-Fetch-Dest",
              "value": "document"
            },
            {
              "name": "Sec-Fetch-Mode",
              "value": "navigate"
            },
            {
              "name": "Sec-Fetch-Site",
              "value": "cross-site"
            },
            {
              "name": "Priority",
              "value": "u=1"
            }
          ],
          "cookies": [
            {
              "name": "categories",
              "value": "general"
            },
            {
              "name": "language",
              "value": "auto"
            },
            {
              "name": "locale",
              "value": "en"
            },
            {
              "name": "autocomplete",
              "value": ""
            },
            {
              "name": "image_proxy",
              "value": "1"
            },
            {
              "name": "method",
              "value": "POST"
            },
            {
              "name": "safesearch",
              "value": "0"
            },
            {
              "name": "theme",
              "value": "simple"
            },
            {
              "name": "results_on_new_tab",
              "value": "0"
            },
            {
              "name": "doi_resolver",
              "value": "oadoi.org"
            },
            {
              "name": "simple_style",
              "value": "auto"
            },
            {
              "name": "center_alignment",
              "value": "0"
            },
            {
              "name": "advanced_search",
              "value": "0"
            },
            {
              "name": "query_in_title",
              "value": "0"
            },
            {
              "name": "infinite_scroll",
              "value": "0"
            },
            {
              "name": "search_on_category_select",
              "value": "1"
            },
            {
              "name": "hotkeys",
              "value": "default"
            },
            {
              "name": "disabled_engines",
              "value": ""
            },
            {
              "name": "enabled_engines",
              "value": ""
            },
            {
              "name": "disabled_plugins",
              "value": ""
            },
            {
              "name": "enabled_plugins",
              "value": ""
            },
            {
              "name": "tokens",
              "value": ""
            },
            {
              "name": "maintab",
              "value": "on"
            },
            {
              "name": "enginetab",
              "value": "on"
            },
            {
              "name": "preferences",
              "value": ""
            },
            {
              "name": "argocd.token",
              "value": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJhcmdvY2QiLCJzdWIiOiJhZG1pbjpsb2dpbiIsImV4cCI6MTcxODI3NTcxMywibmJmIjoxNzE4MTg5MzEzLCJpYXQiOjE3MTgxODkzMTMsImp0aSI6IjU3MjFlOGIxLTIwNDgtNDExMi04ZTExLTAxZDhmNmEwZTY3MyJ9.rbR6ToBtsVPXYkBcqiAxEvP29HYTJL_dHKfmWV08QTA"
            },
            {
              "name": "token",
              "value": "eyJhbGciOiJSUzI1NiIsImtpZCI6IjNqXzAzcmxoY2ZnOEI4SHZ1NzMwZndLQkRPbnlYMmFvRXFYR0pubTFiUkUifQ.eyJhdWQiOlsiaHR0cHM6Ly8xMC4xMC4xMC4xNDI6NjQ0MyJdLCJleHAiOjE3MTgxOTQ5MjksImlhdCI6MTcxODE5MTMyOSwiaXNzIjoiaHR0cHM6Ly8xMC4xMC4xMC4xNDI6NjQ0MyIsImp0aSI6IjdkNDIxMjk1LTNkZTMtNDNiNy1hOWU2LTRlYmQ0MjVhMDg4OSIsImt1YmVybmV0ZXMuaW8iOnsibmFtZXNwYWNlIjoia3ViZXJuZXRlcy1kYXNoYm9hcmQiLCJzZXJ2aWNlYWNjb3VudCI6eyJuYW1lIjoiYWRtaW4tdXNlciIsInVpZCI6ImU0NTIwYzU0LWE2OWEtNDk5OC1iNGNmLWQ5NmUzZDU1MWRmZiJ9fSwibmJmIjoxNzE4MTkxMzI5LCJzdWIiOiJzeXN0ZW06c2VydmljZWFjY291bnQ6a3ViZXJuZXRlcy1kYXNoYm9hcmQ6YWRtaW4tdXNlciJ9.JWpeuiCv03PqVPxpJo9sO-wL8aew1qS-99ALAWt1AksLib5P4pfoxvoav81xk-04ZlNJ6BlYi3lv_uBEG0GoSHTGL_VKW2D90StsIYn3d74tUn4qbRwNtN-ur9TVWuv8dP47BOiV13Hjiki8vhy2EYe_6D0uvhsG_8grlokAdGk9DjYfn6p37ob4nnA78dXONqi4sr7I9i6soYWKSzU65cluvQj6f77iVN4xO6fEnrioIeunyt85Jz7s7OPqSX4waJXcOdi2N1G8iMSfdAXCEkhpFSdPnXGMURK1ItxAs08BRUDtqtnU7UeE7d-yY4VAudTM0IWGoTfPuHocG0oDY7s9n1CQStJUYxbRXEd8VUojVS_uY5zqw7EWpCxb3wdV_MtfBeWzK4HHdVQh8jW39jpGISSG2wnPkQM7M7mAUDZIEv-28HUouNV9MAYAlU6fKj_OAwsqIP4d3tEUK3ecphYYOZVHES38w4KyCh5Woge1SPSC9AssxbMwxdb4tfPH2Bxs29cFJS-yNGSpBbEHi9NAV-03Bzrloij3iuJ0Zc-XpBUtyE3d3dAy1ETsW-ZGc9eVUJP0CbmXU2YCulPmDvGHJMQYmcvOFYI-bUy0mfTTdcbkeVIZuX9cSXiMc22-juaQMncGDw5lLrDgkHcQEc-Ic7hVNaSDUYSZb0WtYsI"
            }
          ],
          "queryString": [],
          "headersSize": 2421
        },
        "response": {
          "status": 500,
          "statusText": "Internal Server Error",
          "httpVersion": "HTTP/1.1",
          "headers": [
            {
              "name": "Content-Length",
              "value": "21"
            },
            {
              "name": "Content-Type",
              "value": "text/html; charset=utf-8"
            },
            {
              "name": "Date",
              "value": "Wed, 12 Jun 2024 13:43:14 GMT"
            },
            {
              "name": "Etag",
              "value": "\"66fci67lppl\""
            },
            {
              "name": "Server",
              "value": "Caddy"
            },
            {
              "name": "Vary",
              "value": "Accept-Encoding"
            },
            {
              "name": "X-Powered-By",
              "value": "Next.js"
            }
          ],
          "cookies": [],
          "content": {
            "mimeType": "text/html; charset=utf-8",
            "size": 21,
            "text": "Internal Server Error"
          },
          "redirectURL": "",
          "headersSize": 217,
          "bodySize": 238
        },
        "cache": {},
        "timings": {
          "blocked": 0,
          "dns": 0,
          "connect": 0,
          "ssl": 0,
          "send": 0,
          "wait": 45,
          "receive": 0
        },
        "time": 45,
        "_securityState": "insecure",
        "serverIPAddress": "127.0.0.1",
        "connection": "3000",
        "pageref": "page_1"
      },
      {
        "startedDateTime": "2024-06-12T15:43:14.843+02:00",
        "request": {
          "bodySize": 0,
          "method": "GET",
          "url": "http://localhost:3000/favicon.ico",
          "httpVersion": "HTTP/1.1",
          "headers": [
            {
              "name": "Host",
              "value": "localhost:3000"
            },
            {
              "name": "User-Agent",
              "value": "Mozilla/5.0 (X11; Linux x86_64; rv:126.0) Gecko/20100101 Firefox/126.0"
            },
            {
              "name": "Accept",
              "value": "image/avif,image/webp,*/*"
            },
            {
              "name": "Accept-Language",
              "value": "en-US,en;q=0.5"
            },
            {
              "name": "Accept-Encoding",
              "value": "gzip, deflate, br, zstd"
            },
            {
              "name": "Connection",
              "value": "keep-alive"
            },
            {
              "name": "Referer",
              "value": "http://localhost:3000/"
            },
            {
              "name": "Cookie",
              "value": "categories=general; language=auto; locale=en; autocomplete=; image_proxy=1; method=POST; safesearch=0; theme=simple; results_on_new_tab=0; doi_resolver=oadoi.org; simple_style=auto; center_alignment=0; advanced_search=0; query_in_title=0; infinite_scroll=0; search_on_category_select=1; hotkeys=default; disabled_engines=; enabled_engines=; disabled_plugins=; enabled_plugins=; tokens=; maintab=on; enginetab=on; preferences=; argocd.token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJhcmdvY2QiLCJzdWIiOiJhZG1pbjpsb2dpbiIsImV4cCI6MTcxODI3NTcxMywibmJmIjoxNzE4MTg5MzEzLCJpYXQiOjE3MTgxODkzMTMsImp0aSI6IjU3MjFlOGIxLTIwNDgtNDExMi04ZTExLTAxZDhmNmEwZTY3MyJ9.rbR6ToBtsVPXYkBcqiAxEvP29HYTJL_dHKfmWV08QTA; token=eyJhbGciOiJSUzI1NiIsImtpZCI6IjNqXzAzcmxoY2ZnOEI4SHZ1NzMwZndLQkRPbnlYMmFvRXFYR0pubTFiUkUifQ.eyJhdWQiOlsiaHR0cHM6Ly8xMC4xMC4xMC4xNDI6NjQ0MyJdLCJleHAiOjE3MTgxOTQ5MjksImlhdCI6MTcxODE5MTMyOSwiaXNzIjoiaHR0cHM6Ly8xMC4xMC4xMC4xNDI6NjQ0MyIsImp0aSI6IjdkNDIxMjk1LTNkZTMtNDNiNy1hOWU2LTRlYmQ0MjVhMDg4OSIsImt1YmVybmV0ZXMuaW8iOnsibmFtZXNwYWNlIjoia3ViZXJuZXRlcy1kYXNoYm9hcmQiLCJzZXJ2aWNlYWNjb3VudCI6eyJuYW1lIjoiYWRtaW4tdXNlciIsInVpZCI6ImU0NTIwYzU0LWE2OWEtNDk5OC1iNGNmLWQ5NmUzZDU1MWRmZiJ9fSwibmJmIjoxNzE4MTkxMzI5LCJzdWIiOiJzeXN0ZW06c2VydmljZWFjY291bnQ6a3ViZXJuZXRlcy1kYXNoYm9hcmQ6YWRtaW4tdXNlciJ9.JWpeuiCv03PqVPxpJo9sO-wL8aew1qS-99ALAWt1AksLib5P4pfoxvoav81xk-04ZlNJ6BlYi3lv_uBEG0GoSHTGL_VKW2D90StsIYn3d74tUn4qbRwNtN-ur9TVWuv8dP47BOiV13Hjiki8vhy2EYe_6D0uvhsG_8grlokAdGk9DjYfn6p37ob4nnA78dXONqi4sr7I9i6soYWKSzU65cluvQj6f77iVN4xO6fEnrioIeunyt85Jz7s7OPqSX4waJXcOdi2N1G8iMSfdAXCEkhpFSdPnXGMURK1ItxAs08BRUDtqtnU7UeE7d-yY4VAudTM0IWGoTfPuHocG0oDY7s9n1CQStJUYxbRXEd8VUojVS_uY5zqw7EWpCxb3wdV_MtfBeWzK4HHdVQh8jW39jpGISSG2wnPkQM7M7mAUDZIEv-28HUouNV9MAYAlU6fKj_OAwsqIP4d3tEUK3ecphYYOZVHES38w4KyCh5Woge1SPSC9AssxbMwxdb4tfPH2Bxs29cFJS-yNGSpBbEHi9NAV-03Bzrloij3iuJ0Zc-XpBUtyE3d3dAy1ETsW-ZGc9eVUJP0CbmXU2YCulPmDvGHJMQYmcvOFYI-bUy0mfTTdcbkeVIZuX9cSXiMc22-juaQMncGDw5lLrDgkHcQEc-Ic7hVNaSDUYSZb0WtYsI"
            },
            {
              "name": "Sec-Fetch-Dest",
              "value": "image"
            },
            {
              "name": "Sec-Fetch-Mode",
              "value": "no-cors"
            },
            {
              "name": "Sec-Fetch-Site",
              "value": "same-origin"
            }
          ],
          "cookies": [
            {
              "name": "categories",
              "value": "general"
            },
            {
              "name": "language",
              "value": "auto"
            },
            {
              "name": "locale",
              "value": "en"
            },
            {
              "name": "autocomplete",
              "value": ""
            },
            {
              "name": "image_proxy",
              "value": "1"
            },
            {
              "name": "method",
              "value": "POST"
            },
            {
              "name": "safesearch",
              "value": "0"
            },
            {
              "name": "theme",
              "value": "simple"
            },
            {
              "name": "results_on_new_tab",
              "value": "0"
            },
            {
              "name": "doi_resolver",
              "value": "oadoi.org"
            },
            {
              "name": "simple_style",
              "value": "auto"
            },
            {
              "name": "center_alignment",
              "value": "0"
            },
            {
              "name": "advanced_search",
              "value": "0"
            },
            {
              "name": "query_in_title",
              "value": "0"
            },
            {
              "name": "infinite_scroll",
              "value": "0"
            },
            {
              "name": "search_on_category_select",
              "value": "1"
            },
            {
              "name": "hotkeys",
              "value": "default"
            },
            {
              "name": "disabled_engines",
              "value": ""
            },
            {
              "name": "enabled_engines",
              "value": ""
            },
            {
              "name": "disabled_plugins",
              "value": ""
            },
            {
              "name": "enabled_plugins",
              "value": ""
            },
            {
              "name": "tokens",
              "value": ""
            },
            {
              "name": "maintab",
              "value": "on"
            },
            {
              "name": "enginetab",
              "value": "on"
            },
            {
              "name": "preferences",
              "value": ""
            },
            {
              "name": "argocd.token",
              "value": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJhcmdvY2QiLCJzdWIiOiJhZG1pbjpsb2dpbiIsImV4cCI6MTcxODI3NTcxMywibmJmIjoxNzE4MTg5MzEzLCJpYXQiOjE3MTgxODkzMTMsImp0aSI6IjU3MjFlOGIxLTIwNDgtNDExMi04ZTExLTAxZDhmNmEwZTY3MyJ9.rbR6ToBtsVPXYkBcqiAxEvP29HYTJL_dHKfmWV08QTA"
            },
            {
              "name": "token",
              "value": "eyJhbGciOiJSUzI1NiIsImtpZCI6IjNqXzAzcmxoY2ZnOEI4SHZ1NzMwZndLQkRPbnlYMmFvRXFYR0pubTFiUkUifQ.eyJhdWQiOlsiaHR0cHM6Ly8xMC4xMC4xMC4xNDI6NjQ0MyJdLCJleHAiOjE3MTgxOTQ5MjksImlhdCI6MTcxODE5MTMyOSwiaXNzIjoiaHR0cHM6Ly8xMC4xMC4xMC4xNDI6NjQ0MyIsImp0aSI6IjdkNDIxMjk1LTNkZTMtNDNiNy1hOWU2LTRlYmQ0MjVhMDg4OSIsImt1YmVybmV0ZXMuaW8iOnsibmFtZXNwYWNlIjoia3ViZXJuZXRlcy1kYXNoYm9hcmQiLCJzZXJ2aWNlYWNjb3VudCI6eyJuYW1lIjoiYWRtaW4tdXNlciIsInVpZCI6ImU0NTIwYzU0LWE2OWEtNDk5OC1iNGNmLWQ5NmUzZDU1MWRmZiJ9fSwibmJmIjoxNzE4MTkxMzI5LCJzdWIiOiJzeXN0ZW06c2VydmljZWFjY291bnQ6a3ViZXJuZXRlcy1kYXNoYm9hcmQ6YWRtaW4tdXNlciJ9.JWpeuiCv03PqVPxpJo9sO-wL8aew1qS-99ALAWt1AksLib5P4pfoxvoav81xk-04ZlNJ6BlYi3lv_uBEG0GoSHTGL_VKW2D90StsIYn3d74tUn4qbRwNtN-ur9TVWuv8dP47BOiV13Hjiki8vhy2EYe_6D0uvhsG_8grlokAdGk9DjYfn6p37ob4nnA78dXONqi4sr7I9i6soYWKSzU65cluvQj6f77iVN4xO6fEnrioIeunyt85Jz7s7OPqSX4waJXcOdi2N1G8iMSfdAXCEkhpFSdPnXGMURK1ItxAs08BRUDtqtnU7UeE7d-yY4VAudTM0IWGoTfPuHocG0oDY7s9n1CQStJUYxbRXEd8VUojVS_uY5zqw7EWpCxb3wdV_MtfBeWzK4HHdVQh8jW39jpGISSG2wnPkQM7M7mAUDZIEv-28HUouNV9MAYAlU6fKj_OAwsqIP4d3tEUK3ecphYYOZVHES38w4KyCh5Woge1SPSC9AssxbMwxdb4tfPH2Bxs29cFJS-yNGSpBbEHi9NAV-03Bzrloij3iuJ0Zc-XpBUtyE3d3dAy1ETsW-ZGc9eVUJP0CbmXU2YCulPmDvGHJMQYmcvOFYI-bUy0mfTTdcbkeVIZuX9cSXiMc22-juaQMncGDw5lLrDgkHcQEc-Ic7hVNaSDUYSZb0WtYsI"
            }
          ],
          "queryString": [],
          "headersSize": 0
        },
        "response": {
          "status": 500,
          "statusText": "Internal Server Error",
          "httpVersion": "HTTP/1.1",
          "headers": [
            {
              "name": "Cache-Control",
              "value": "no-cache, no-store, max-age=0, must-revalidate"
            },
            {
              "name": "Content-Length",
              "value": "21"
            },
            {
              "name": "Content-Type",
              "value": "text/html; charset=utf-8"
            },
            {
              "name": "Date",
              "value": "Wed, 12 Jun 2024 13:43:10 GMT"
            },
            {
              "name": "Etag",
              "value": "\"66fci67lppl\""
            },
            {
              "name": "Server",
              "value": "Caddy"
            },
            {
              "name": "Vary",
              "value": "Accept-Encoding"
            },
            {
              "name": "X-Powered-By",
              "value": "Next.js"
            }
          ],
          "cookies": [],
          "content": {
            "mimeType": "text/html; charset=utf-8",
            "size": 21,
            "text": "Internal Server Error"
          },
          "redirectURL": "",
          "headersSize": 0,
          "bodySize": 21
        },
        "cache": {},
        "timings": {
          "blocked": 0,
          "dns": 0,
          "ssl": 0,
          "connect": 0,
          "send": 0,
          "wait": 0,
          "receive": 0
        },
        "time": 0,
        "_securityState": "insecure",
        "pageref": "page_1"
      }
    ]
  }
}
```

**Comment by nilsherzig** [comment]
Damn I should do something about the cookie station on my localhost hahah, I'm out there leaking Argo tokens

**Comment by nilsherzig** [comment]
Well fuck, cleaning my localhost cookies solved the problem. It's always a user error, isn't it haha? You might still want to check your cookie handling, something might be weird

**Comment by nilsherzig** [comment]
Looks like my "locale: auto" cookie crashed this line 

https://github.com/stonith404/pingvin-share/blob/3773432eb5cff3784d36918ab1883413d6adf766/frontend/src/hooks/useTranslate.hook.ts#L20

**Comment by stonith404** [comment]
Sorry for my late response. Thanks for debugging this further, I'll look into it.

**Comment by nilsherzig** [comment]
No problem, enjoying your project otherwise :)
