### ISSUE TITLE
🐛 Bug Report: Can't access it except from its ip address

### ISSUE THREAD

**Issue by Itay1787** [stonith404/pingvin-share#292]
### 👟 Reproduction steps

When I try to access it through my domain behind my reverse proxy I get this error
![תמונה](https://github.com/stonith404/pingvin-share/assets/40241083/7ffad303-d0a4-446f-bd7f-97a0dd32624e)
And nothing can be done.

But everything works when I try to access it via his IP address.
I installed it manually without docker

Logs `pm2 logs pingvin-share-frontend`

```
[TAILING] Tailing last 15 lines for [pingvin-share-frontend] process (change the value with --lines option)
/root/.pm2/logs/pingvin-share-frontend-out.log last 15 lines:
1|pingvin- | > pingvin-share-frontend@0.18.2 start
1|pingvin- | > next start
1|pingvin- | 
1|pingvin- |   ▲ Next.js 13.5.5
1|pingvin- |   - Local:        http://localhost:3000
1|pingvin- | 
1|pingvin- |  ✓ Ready in 3s
1|pingvin- | 
1|pingvin- | > pingvin-share-frontend@0.18.2 start
1|pingvin- | > next start
1|pingvin- | 
1|pingvin- |   ▲ Next.js 13.5.5
1|pingvin- |   - Local:        http://localhost:3000
1|pingvin- | 
1|pingvin- |  ✓ Ready in 5.9s

/root/.pm2/logs/pingvin-share-frontend-error.log last 15 lines:
1|pingvin- |     at context.fetch (file:///opt/pingvin-share/frontend/node_modules/next/dist/server/web/sandbox/context.js:260:38)
1|pingvin- |     at Object.middleware [as handler] (file:///opt/pingvin-share/frontend/.next/server/src/middleware.js:5034:33)
1|pingvin- |     at <unknown> (file:///opt/pingvin-share/frontend/.next/server/src/middleware.js:1948:23)
1|pingvin- |     at AsyncLocalStorage.run (node:async_hooks:346:14)
1|pingvin- |     at Object.wrap (file:///opt/pingvin-share/frontend/.next/server/src/middleware.js:1749:24)
1|pingvin- |     at adapter (file:///opt/pingvin-share/frontend/.next/server/src/middleware.js:1935:53)
1|pingvin- |     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
1|pingvin- | Error [TypeError]: fetch failed
1|pingvin- |     at context.fetch (file:///opt/pingvin-share/frontend/node_modules/next/dist/server/web/sandbox/context.js:260:38)
1|pingvin- |     at Object.middleware [as handler] (file:///opt/pingvin-share/frontend/.next/server/src/middleware.js:5034:33)
1|pingvin- |     at <unknown> (file:///opt/pingvin-share/frontend/.next/server/src/middleware.js:1948:23)
1|pingvin- |     at AsyncLocalStorage.run (node:async_hooks:346:14)
1|pingvin- |     at Object.wrap (file:///opt/pingvin-share/frontend/.next/server/src/middleware.js:1749:24)
1|pingvin- |     at adapter (file:///opt/pingvin-share/frontend/.next/server/src/middleware.js:1935:53)
1|pingvin- |     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

1|pingvin-share-frontend  | Error [TypeError]: fetch failed
1|pingvin-share-frontend  |     at context.fetch (file:///opt/pingvin-share/frontend/node_modules/next/dist/server/web/sandbox/context.js:260:38)
1|pingvin-share-frontend  |     at Object.middleware [as handler] (file:///opt/pingvin-share/frontend/.next/server/src/middleware.js:5034:33)
1|pingvin-share-frontend  |     at <unknown> (file:///opt/pingvin-share/frontend/.next/server/src/middleware.js:1948:23)
1|pingvin-share-frontend  |     at AsyncLocalStorage.run (node:async_hooks:346:14)
1|pingvin-share-frontend  |     at Object.wrap (file:///opt/pingvin-share/frontend/.next/server/src/middleware.js:1749:24)
1|pingvin-share-frontend  |     at adapter (file:///opt/pingvin-share/frontend/.next/server/src/middleware.js:1935:53)
1|pingvin-share-frontend  |     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
1|pingvin-share-frontend  | Error [TypeError]: fetch failed
1|pingvin-share-frontend  |     at context.fetch (file:///opt/pingvin-share/frontend/node_modules/next/dist/server/web/sandbox/context.js:260:38)
1|pingvin-share-frontend  |     at Object.middleware [as handler] (file:///opt/pingvin-share/frontend/.next/server/src/middleware.js:5034:33)
1|pingvin-share-frontend  |     at <unknown> (file:///opt/pingvin-share/frontend/.next/server/src/middleware.js:1948:23)
1|pingvin-share-frontend  |     at AsyncLocalStorage.run (node:async_hooks:346:14)
1|pingvin-share-frontend  |     at Object.wrap (file:///opt/pingvin-share/frontend/.next/server/src/middleware.js:1749:24)
1|pingvin-share-frontend  |     at adapter (file:///opt/pingvin-share/frontend/.next/server/src/middleware.js:1935:53)
1|pingvin-share-frontend  |     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
1|pingvin-share-frontend  | Error [TypeError]: fetch failed
1|pingvin-share-frontend  |     at context.fetch (file:///opt/pingvin-share/frontend/node_modules/next/dist/server/web/sandbox/context.js:260:38)
1|pingvin-share-frontend  |     at Object.middleware [as handler] (file:///opt/pingvin-share/frontend/.next/server/src/middleware.js:5034:33)
1|pingvin-share-frontend  |     at <unknown> (file:///opt/pingvin-share/frontend/.next/server/src/middleware.js:1948:23)
1|pingvin-share-frontend  |     at AsyncLocalStorage.run (node:async_hooks:346:14)
1|pingvin-share-frontend  |     at Object.wrap (file:///opt/pingvin-share/frontend/.next/server/src/middleware.js:1749:24)
1|pingvin-share-frontend  |     at adapter (file:///opt/pingvin-share/frontend/.next/server/src/middleware.js:1935:53)
1|pingvin-share-frontend  |     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
1|pingvin-share-frontend  | Error [TypeError]: fetch failed
1|pingvin-share-frontend  |     at context.fetch (file:///opt/pingvin-share/frontend/node_modules/next/dist/server/web/sandbox/context.js:260:38)
1|pingvin-share-frontend  |     at Object.middleware [as handler] (file:///opt/pingvin-share/frontend/.next/server/src/middleware.js:5034:33)
1|pingvin-share-frontend  |     at <unknown> (file:///opt/pingvin-share/frontend/.next/server/src/middleware.js:1948:23)
1|pingvin-share-frontend  |     at AsyncLocalStorage.run (node:async_hooks:346:14)
1|pingvin-share-frontend  |     at Object.wrap (file:///opt/pingvin-share/frontend/.next/server/src/middleware.js:1749:24)
1|pingvin-share-frontend  |     at adapter (file:///opt/pingvin-share/frontend/.next/server/src/middleware.js:1935:53)
1|pingvin-share-frontend  |     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
1|pingvin-share-frontend  | Error [TypeError]: fetch failed
1|pingvin-share-frontend  |     at context.fetch (file:///opt/pingvin-share/frontend/node_modules/next/dist/server/web/sandbox/context.js:260:38)
1|pingvin-share-frontend  |     at Object.middleware [as handler] (file:///opt/pingvin-share/frontend/.next/server/src/middleware.js:5034:33)
1|pingvin-share-frontend  |     at <unknown> (file:///opt/pingvin-share/frontend/.next/server/src/middleware.js:1948:23)
1|pingvin-share-frontend  |     at AsyncLocalStorage.run (node:async_hooks:346:14)
1|pingvin-share-frontend  |     at Object.wrap (file:///opt/pingvin-share/frontend/.next/server/src/middleware.js:1749:24)
1|pingvin-share-frontend  |     at adapter (file:///opt/pingvin-share/frontend/.next/server/src/middleware.js:1935:53)
1|pingvin-share-frontend  |     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
^C

```

`pm2 logs pingvin-share-backend`

```
[TAILING] Tailing last 15 lines for [pingvin-share-backend] process (change the value with --lines option)
/root/.pm2/logs/pingvin-share-backend-error.log last 15 lines:
0|pingvin- | npm ERR!   npm run
0|pingvin- | 
0|pingvin- | npm ERR! A complete log of this run can be found in: /root/.npm/_logs/2023-10-18T20_54_57_493Z-debug-0.log
0|pingvin- | npm ERR! Missing script: "prod"
0|pingvin- | npm ERR! 
0|pingvin- | npm ERR! To see a list of scripts, run:
0|pingvin- | npm ERR!   npm run
0|pingvin- | 
0|pingvin- | npm ERR! A complete log of this run can be found in: /root/.npm/_logs/2023-10-18T20_54_58_324Z-debug-0.log
0|pingvin- | npm ERR! Missing script: "prod"
0|pingvin- | npm ERR! 
0|pingvin- | npm ERR! To see a list of scripts, run:
0|pingvin- | npm ERR!   npm run
0|pingvin- | 
0|pingvin- | npm ERR! A complete log of this run can be found in: /root/.npm/_logs/2023-10-18T20_54_59_171Z-debug-0.log

/root/.pm2/logs/pingvin-share-backend-out.log last 15 lines:
0|pingvin- | [Nest] 652  - 10/18/2023, 9:02:50 PM     LOG [RoutesResolver] ConfigController {/api/configs}: +0ms
0|pingvin- | [Nest] 652  - 10/18/2023, 9:02:50 PM     LOG [RouterExplorer] Mapped {/api/configs, GET} route +1ms
0|pingvin- | [Nest] 652  - 10/18/2023, 9:02:50 PM     LOG [RouterExplorer] Mapped {/api/configs/admin/:category, GET} route +1ms
0|pingvin- | [Nest] 652  - 10/18/2023, 9:02:50 PM     LOG [RouterExplorer] Mapped {/api/configs/admin, PATCH} route +0ms
0|pingvin- | [Nest] 652  - 10/18/2023, 9:02:50 PM     LOG [RouterExplorer] Mapped {/api/configs/admin/testEmail, POST} route +1ms
0|pingvin- | [Nest] 652  - 10/18/2023, 9:02:50 PM     LOG [RouterExplorer] Mapped {/api/configs/admin/logo, POST} route +1ms
0|pingvin- | [Nest] 652  - 10/18/2023, 9:02:50 PM     LOG [RoutesResolver] UserController {/api/users}: +0ms
0|pingvin- | [Nest] 652  - 10/18/2023, 9:02:50 PM     LOG [RouterExplorer] Mapped {/api/users/me, GET} route +1ms
0|pingvin- | [Nest] 652  - 10/18/2023, 9:02:50 PM     LOG [RouterExplorer] Mapped {/api/users/me, PATCH} route +1ms
0|pingvin- | [Nest] 652  - 10/18/2023, 9:02:50 PM     LOG [RouterExplorer] Mapped {/api/users/me, DELETE} route +0ms
0|pingvin- | [Nest] 652  - 10/18/2023, 9:02:50 PM     LOG [RouterExplorer] Mapped {/api/users, GET} route +1ms
0|pingvin- | [Nest] 652  - 10/18/2023, 9:02:50 PM     LOG [RouterExplorer] Mapped {/api/users, POST} route +0ms
0|pingvin- | [Nest] 652  - 10/18/2023, 9:02:50 PM     LOG [RouterExplorer] Mapped {/api/users/:id, PATCH} route +1ms
0|pingvin- | [Nest] 652  - 10/18/2023, 9:02:50 PM     LOG [RouterExplorer] Mapped {/api/users/:id, DELETE} route +0ms
0|pingvin- | [Nest] 652  - 10/18/2023, 9:02:50 PM     LOG [NestApplication] Nest application successfully started +44ms

^C
```

### 👍 Expected behavior

that it will work from my domain

### 👎 Actual Behavior

I can't access it except from its IP:3000

### 🌐 Browser

Firefox

**Comment by stonith404** [comment]
Can you share your reverse proxy config?

**Comment by Itay1787** [comment]
> Can you share your reverse proxy config?

```
location / {

#Proxy Headers
proxy_set_headerHost $host;
proxy_set_headerX-Real-IP $remote_addr;
proxy_set_headerX-Forwarded-For $proxy_add_x_forwarded_for;
proxy_set_headerX-Forwarded-Proto $scheme;
add_header Strict-Transport-Security "max-age=31536000; includeSubdomains; preload";
set $x_frame_options "SAMEORIGIN";
client_max_body_size 0;
proxy_max_temp_file_size 0;

#Proxy

       .......

}
```

**Comment by stonith404** [comment]
The proxy part too, please. 

What happens when you visit `https://your-domain/api/configs`and `http://your-frontend-ip/api/configs`?

**Comment by Itay1787** [comment]
> The proxy part too, please.

```
location / {

  #Proxy Headers
      proxy_set_header        Host $host;
      proxy_set_header        X-Real-IP $remote_addr;
      proxy_set_header        X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header        X-Forwarded-Proto $scheme;
      add_header Strict-Transport-Security "max-age=31536000; includeSubdomains; preload";
      set $x_frame_options "SAMEORIGIN";
      client_max_body_size 0;
      proxy_max_temp_file_size 0;

#Proxy
    proxy_pass          http://192.168.3.10:3000;
    proxy_read_timeout  90;

    proxy_redirect      http://192.168.3.10:3000 https://sub.my.domain;
}
```




> What happens when you visit `https://your-domain/api/configs`and `http://your-frontend-ip/api/configs`?


Both show the same thing
![Screenshot 2023-10-26 at 0 34 31](https://github.com/stonith404/pingvin-share/assets/40241083/ad89f82f-48e8-4f18-986a-6426921f4528)

**Comment by stonith404** [comment]
@Itay1787 Could you test it again with the `stonith404/pingvin-share:development` image and share the logs again?

**Comment by Itay1787** [comment]
> @Itay1787 Could you test it again with the `stonith404/pingvin-share:development` image and share the logs again?

Hi, sorry it took me so long to reply back.
I decided to just reinstall everything to the new version and now it seems to work.
But I did get some warnings during the installation

backend
npm install
<img width="953" alt="Screenshot 2023-11-20 at 22 24 49" src="https://github.com/stonith404/pingvin-share/assets/40241083/d7ff0acb-484c-4b52-b932-6750c339e805">

frontend
npm install
<img width="482" alt="Screenshot 2023-11-20 at 22 29 16" src="https://github.com/stonith404/pingvin-share/assets/40241083/3a9360fa-3058-4582-8ba6-1d895b0382b9">

frontend
npm run build
<img width="908" alt="Screenshot 2023-11-20 at 22 29 55" src="https://github.com/stonith404/pingvin-share/assets/40241083/86cbac8c-24ca-406b-b3bd-e27d20556dcd">

**Comment by stonith404** [comment]
Great. The warnings are expected.
