### ISSUE TITLE
🐛 Bug Report: Discord SSO

### ISSUE THREAD

**Issue by ukdaaan** [stonith404/pingvin-share#302]
### 👟 Reproduction steps

Enable the Discord SSO with correct callback urls

### 👍 Expected behavior

SSO process should complete without issues. (Other IDPs are working as expected without issues)

### 👎 Actual Behavior

SSO fails to link accounts with error 500, docker console logs below.

```
[Nest] 45  - 10/29/2023, 6:34:12 PM   ERROR [ExceptionsHandler] Cannot read properties of undefined (reading 'password')
TypeError: Cannot read properties of undefined (reading 'password')
    at UserController.getCurrentUser (/opt/app/backend/dist/src/user/user.controller.js:32:38)
    at /opt/app/backend/node_modules/@nestjs/core/router/router-execution-context.js:38:29
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
[Nest] 45  - 10/29/2023, 6:34:16 PM   ERROR [ExceptionsHandler] Cannot read properties of undefined (reading 'password')
TypeError: Cannot read properties of undefined (reading 'password')
    at UserController.getCurrentUser (/opt/app/backend/dist/src/user/user.controller.js:32:38)
    at /opt/app/backend/node_modules/@nestjs/core/router/router-execution-context.js:38:29
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
[Nest] 45  - 10/29/2023, 6:34:16 PM   ERROR [ExceptionsHandler] Cannot read properties of undefined (reading 'password')
TypeError: Cannot read properties of undefined (reading 'password')
    at UserController.getCurrentUser (/opt/app/backend/dist/src/user/user.controller.js:32:38)
    at /opt/app/backend/node_modules/@nestjs/core/router/router-execution-context.js:38:29
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
[Nest] 45  - 10/29/2023, 6:34:18 PM   ERROR [ExceptionsHandler] Cannot read properties of undefined (reading 'password')
TypeError: Cannot read properties of undefined (reading 'password')
    at UserController.getCurrentUser (/opt/app/backend/dist/src/user/user.controller.js:32:38)
    at /opt/app/backend/node_modules/@nestjs/core/router/router-execution-context.js:38:29
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
[Nest] 45  - 10/29/2023, 6:34:19 PM   ERROR [ExceptionsHandler] Cannot read properties of undefined (reading 'password')
TypeError: Cannot read properties of undefined (reading 'password')
    at UserController.getCurrentUser (/opt/app/backend/dist/src/user/user.controller.js:32:38)
    at /opt/app/backend/node_modules/@nestjs/core/router/router-execution-context.js:38:29
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
[Nest] 45  - 10/29/2023, 6:34:23 PM   ERROR [ExceptionsHandler] Cannot read properties of undefined (reading 'password')
TypeError: Cannot read properties of undefined (reading 'password')
    at UserController.getCurrentUser (/opt/app/backend/dist/src/user/user.controller.js:32:38)
    at /opt/app/backend/node_modules/@nestjs/core/router/router-execution-context.js:38:29
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
[Nest] 45  - 10/29/2023, 6:34:24 PM   ERROR [ExceptionsHandler] Cannot read properties of undefined (reading 'password')
TypeError: Cannot read properties of undefined (reading 'password')
    at UserController.getCurrentUser (/opt/app/backend/dist/src/user/user.controller.js:32:38)
    at /opt/app/backend/node_modules/@nestjs/core/router/router-execution-context.js:38:29
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
[Nest] 45  - 10/29/2023, 6:34:24 PM   ERROR [ExceptionsHandler] Cannot read properties of undefined (reading 'password')
TypeError: Cannot read properties of undefined (reading 'password')
    at UserController.getCurrentUser (/opt/app/backend/dist/src/user/user.controller.js:32:38)
    at /opt/app/backend/node_modules/@nestjs/core/router/router-execution-context.js:38:29
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
[Nest] 45  - 10/29/2023, 6:34:35 PM   ERROR [ExceptionsHandler] 
Invalid `this.prisma.oAuthUser.create()` invocation in
/opt/app/backend/dist/src/oauth/oauth.service.js:77:37
  74         `provider_${provider}`,
������
  75     ]);
  76 }
→ 77 await this.prisma.oAuthUser.create({
       data: {
         userId: "bc026ba0-b75a-4eea-9200-d2349a8203f7",
         provider: "discord",
         providerUsername: undefined,
     +   providerUserId: String
       }
     })
Argument `providerUserId` is missing.
PrismaClientValidationError: 
Invalid `this.prisma.oAuthUser.create()` invocation in
/opt/app/backend/dist/src/oauth/oauth.service.js:77:37
  74         `provider_${provider}`,
������
  75     ]);
  76 }
→ 77 await this.prisma.oAuthUser.create({
       data: {
         userId: "bc026ba0-b75a-4eea-9200-d2349a8203f7",
         provider: "discord",
         providerUsername: undefined,
     +   providerUserId: String
       }
     })
Argument `providerUserId` is missing.
    at Ur (/opt/app/backend/node_modules/@prisma/client/runtime/library.js:115:5803)
    at zr.handleRequestError (/opt/app/backend/node_modules/@prisma/client/runtime/library.js:122:8007)
    at zr.handleAndLogRequestError (/opt/app/backend/node_modules/@prisma/client/runtime/library.js:122:7697)
    at zr.request (/opt/app/backend/node_modules/@prisma/client/runtime/library.js:122:7307)
    at async OAuthService.link (/opt/app/backend/dist/src/oauth/oauth.service.js:77:9)
    at async OAuthController.callback (/opt/app/backend/dist/src/oauth/oauth.controller.js:53:13)
```

### 🌐 Browser

Firefox & Safari (MacOS)

**Comment by stonith404** [comment]
@zz5840 Do you maybe know why this occurs?

**Comment by zz5840** [comment]
@stonith404 I'll look in it now.

**Comment by zz5840** [comment]
@ukdaaan Your account info, as shown below:
![image](https://github.com/stonith404/pingvin-share/assets/16662647/2e8d9e31-c4b1-40ca-81b7-0dbe1f3dba7d)

**Comment by zz5840** [comment]
@ukdaaan I see, it seems that the provider can't get both user id and user name. Does this bug affect only your account or all accounts in your app?

**Comment by zz5840** [comment]
@ukdaaan Sorry, but I can't get any helpful information from the error log, maybe more sensitive information is needed. If you're willing to help me locate the bug, please join my [discord server](https://discord.gg/4heDwq7S) so that I can take a deeper look in it.

**Comment by stonith404** [comment]
@ukdaaan It should be fixed. Can you try the image `stonith404/pingvin-share:development`?

**Comment by stonith404** [comment]
Great, the fix will be released ASAP. Make sure to switch back to the `latest` image as soon as the newest release is released.

CC: @zz5840
