### ISSUE TITLE
🐛 Bug Report: frontend error on first starup

### ISSUE THREAD

**Issue by dnielso5** [stonith404/pingvin-share#391]
### 👟 Reproduction steps

run: pm2 start --name="pingvin-share-backend" npm -- run prod

### 👍 Expected behavior

front end loading

### 👎 Actual Behavior

errors from error log:

0 verbose cli /usr/bin/node /usr/local/lib/node_modules/pm2/lib/ProcessContainerFork.js
1 info using npm@9.5.0
2 info using node@v18.14.2
3 timing npm:load:whichnode Completed in 15ms
4 timing config:load:defaults Completed in 6ms
5 timing config:load:file:/usr/lib/node_modules/npm/npmrc Completed in 25ms
6 timing config:load:builtin Completed in 25ms
7 timing config:load:cli Completed in 7ms
8 timing config:load:env Completed in 1ms
9 timing config:load:file:/pingvin-share/frontend/.npmrc Completed in 0ms
10 timing config:load:project Completed in 12ms
11 timing config:load:file:/home/dnielson/.npmrc Completed in 0ms
12 timing config:load:user Completed in 1ms
13 timing config:load:file:/usr/etc/npmrc Completed in 3ms
14 timing config:load:global Completed in 4ms
15 timing config:load:setEnvs Completed in 5ms
16 timing config:load Completed in 64ms
17 timing npm:load:configload Completed in 65ms
18 timing npm:load:mkdirpcache Completed in 3ms
19 timing npm:load:mkdirplogs Completed in 3ms
20 verbose title npm run start~
21 verbose argv "run" "start~"
22 timing npm:load:setTitle Completed in 9ms
23 timing config:load:flatten Completed in 12ms
24 timing npm:load:display Completed in 17ms
25 verbose logfile logs-max:10 dir:/home/dnielson/.npm/_logs/2024-01-22T20_29_38_866Z-
26 verbose logfile /home/dnielson/.npm/_logs/2024-01-22T20_29_38_866Z-debug-0.log
27 timing npm:load:logFile Completed in 32ms
28 timing npm:load:timers Completed in 0ms
29 timing npm:load:configScope Completed in 0ms
30 timing npm:load Completed in 148ms
31 silly logfile start cleaning logs, removing 1 files
32 silly logfile done cleaning log files
33 timing command:run Completed in 44ms
34 verbose stack Error: Missing script: "start~"
34 verbose stack
34 verbose stack Did you mean one of these?
34 verbose stack     npm star # Mark your favorite packages
34 verbose stack     npm stars # View packages marked as favorites
34 verbose stack     npm start # Start a package
34 verbose stack
34 verbose stack To see a list of scripts, run:
34 verbose stack   npm run
34 verbose stack     at RunScript.run (/usr/lib/node_modules/npm/lib/commands/run-script.js:99:13)
34 verbose stack     at async module.exports (/usr/lib/node_modules/npm/lib/cli.js:134:5)
35 verbose cwd /pingvin-share/frontend
36 verbose Linux 5.14.0-407.el9.x86_64
37 verbose node v18.14.2
38 verbose npm  v9.5.0
39 error Missing script: "start~"
39 error
39 error Did you mean one of these?
39 error     npm star # Mark your favorite packages
39 error     npm stars # View packages marked as favorites
39 error     npm start # Start a package
39 error
39 error To see a list of scripts, run:
39 error   npm run
40 verbose exit 1
41 timing npm Completed in 301ms
42 verbose code 1
43 error A complete log of this run can be found in:
43 error     /home/dnielson/.npm/_logs/2024-01-22T20_29_38_866Z-debug-0.log

### 🌐 Browser

Chrome

**Comment by dnielso5** [comment]
This is a manual install with NPM.

**Comment by dnielso5** [comment]
Got approval to run this in docker instead. no longer needed.
