### ISSUE TITLE
🐛 Bug Report: Errors while uploading files

### ISSUE THREAD

**Issue by plague-doctor** [stonith404/pingvin-share#394]
### 👟 Reproduction steps

While uploading multiple files (in this case approx 100 JPG files) I get this error:

```
[...]
(node:33) Warning: No such label 'default' for console.timeEnd()
(node:33) Warning: Label 'default' already exists for console.time()
{ diskFileSize: 0, chunkSize: 20971520, expectedChunkIndex: 0 }
{ diskFileSize: 0, chunkSize: 20971520, expectedChunkIndex: 0 }
[Nest] 33  - 01/24/2024, 11:54:58 PM   ERROR [ExceptionsHandler] 
Invalid `this.prisma.file.create()` invocation in
/opt/app/backend/dist/src/file/file.service.js:70:36
  67 if (isLastChunk) {
  68     fs.renameSync(`${constants_1.SHARE_DIRECTORY}/${shareId}/${file.id}.tmp-chunk`, `${constants_1.SHARE_DIRECTORY}/${shareId}/${file.id}`);
  69     const fileSize = fs.statSync(`${constants_1.SHARE_DIRECTORY}/${shareId}/${file.id}`).size;
→ 70     await this.prisma.file.create(
Error occurred during query execution:
ConnectorError(ConnectorError { user_facing_error: None, kind: ConnectionError(Timed out during query execution.), transient: false })
PrismaClientUnknownRequestError: 
Invalid `this.prisma.file.create()` invocation in
/opt/app/backend/dist/src/file/file.service.js:70:36
  67 if (isLastChunk) {
  68     fs.renameSync(`${constants_1.SHARE_DIRECTORY}/${shareId}/${file.id}.tmp-chunk`, `${constants_1.SHARE_DIRECTORY}/${shareId}/${file.id}`);
  69     const fileSize = fs.statSync(`${constants_1.SHARE_DIRECTORY}/${shareId}/${file.id}`).size;
→ 70     await this.prisma.file.create(
Error occurred during query execution:
ConnectorError(ConnectorError { user_facing_error: None, kind: ConnectionError(Timed out during query execution.), transient: false })
    at zr.handleRequestError (/opt/app/backend/node_modules/@prisma/client/runtime/library.js:122:8480)
    at zr.handleAndLogRequestError (/opt/app/backend/node_modules/@prisma/client/runtime/library.js:122:7697)
    at zr.request (/opt/app/backend/node_modules/@prisma/client/runtime/library.js:122:7307)
    at async FileService.create (/opt/app/backend/dist/src/file/file.service.js:70:13)
    at async FileController.create (/opt/app/backend/dist/src/file/file.controller.js:32:22)
default: 71.379ms
{ diskFileSize: 0, chunkSize: 20971520, expectedChunkIndex: 0 }
[...]
```

it looks like the affected files are re-uploaded. Just log file is being polluted with those errors.

### 👍 Expected behavior

Well... No errors :-)

### 👎 Actual Behavior

As above

### 🌐 Browser

All of them (Linux OS)

**Comment by stonith404** [comment]
This only occurs with the development image, right?

**Comment by plague-doctor** [comment]
Yes, that's right. However, I haven't tested the `latest` image yet.

**Comment by stonith404** [comment]
Ok, could you test it with the latest image?

**Comment by kevocl** [comment]
@stonith404 I think I'm having the same issue.

I try to upload 100+ (small) files and Pingvin Share states there has been an error uploading a file and then seems to lock up.

I'm using the 'latest' docker image.

The logs show the following:

```
thread 'tokio-runtime-worker' panicked at libs/user-facing-errors/src/quaint.rs:178:18:
internal error: entered unreachable code
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
[Nest] 39  - 06/30/2024, 7:16:30 PM   ERROR [ExceptionsHandler]
Invalid `this.prisma.file.create()` invocation in
/opt/app/backend/dist/src/file/file.service.js:64:36

  61 if (isLastChunk) {
  62     fs.renameSync(`${constants_1.SHARE_DIRECTORY}/${shareId}/${file.id}.tmp-chunk`, `${constants_1.SHARE_DIRECTORY}/${shareId}/${file.id}`);
  63     const fileSize = fs.statSync(`${constants_1.SHARE_DIRECTORY}/${shareId}/${file.id}`).size;
→ 64     await this.prisma.file.create(
internal error: entered unreachable code

This is a non-recoverable error which probably happens when the Prisma Query Engine has a panic.

https://github.com/prisma/prisma/issues/new...=bug_report.yml
If you want the Prisma team to look into it, please open the link above 🙏
To increase the chance of success, please post your schema and a snippet of
how you used Prisma Client in the issue.

PrismaClientRustPanicError:
Invalid `this.prisma.file.create()` invocation in
/opt/app/backend/dist/src/file/file.service.js:64:36

  61 if (isLastChunk) {
  62     fs.renameSync(`${constants_1.SHARE_DIRECTORY}/${shareId}/${file.id}.tmp-chunk`, `${constants_1.SHARE_DIRECTORY}/${shareId}/${file.id}`);
  63     const fileSize = fs.statSync(`${constants_1.SHARE_DIRECTORY}/${shareId}/${file.id}`).size;
→ 64     await this.prisma.file.create(
internal error: entered unreachable code

This is a non-recoverable error which probably happens when the Prisma Query Engine has a panic.

https://github.com/prisma/prisma/issues/new...=bug_report.yml

If you want the Prisma team to look into it, please open the link above 🙏
To increase the chance of success, please post your schema and a snippet of
how you used Prisma Client in the issue.

    at In.handleRequestError (/opt/app/backend/node_modules/@prisma/client/runtime/library.js:122:7238)
    at In.handleAndLogRequestError (/opt/app/backend/node_modules/@prisma/client/runtime/library.js:122:6211)
    at In.request (/opt/app/backend/node_modules/@prisma/client/runtime/library.js:122:5919)
    at async l (/opt/app/backend/node_modules/@prisma/client/runtime/library.js:127:11167)
    at async FileService.create (/opt/app/backend/dist/src/file/file.service.js:64:13)
    at async FileController.create (/opt/app/backend/dist/src/file/file.controller.js:30:16)
[Nest] 39  - 06/30/2024, 7:16:30 PM   ERROR [ExceptionsHandler]
Invalid `this.prisma.file.create()` invocation in
/opt/app/backend/dist/src/file/file.service.js:64:36

  61 if (isLastChunk) {
  62     fs.renameSync(`${constants_1.SHARE_DIRECTORY}/${shareId}/${file.id}.tmp-chunk`, `${constants_1.SHARE_DIRECTORY}/${shareId}/${file.id}`);
  63     const fileSize = fs.statSync(`${constants_1.SHARE_DIRECTORY}/${shareId}/${file.id}`).size;
→ 64     await this.prisma.file.create(
Error in connector: Error querying the database: Error code 1: SQL error or missing database
PrismaClientUnknownRequestError:
Invalid `this.prisma.file.create()` invocation in
/opt/app/backend/dist/src/file/file.service.js:64:36

  61 if (isLastChunk) {
  62     fs.renameSync(`${constants_1.SHARE_DIRECTORY}/${shareId}/${file.id}.tmp-chunk`, `${constants_1.SHARE_DIRECTORY}/${shareId}/${file.id}`);
  63     const fileSize = fs.statSync(`${constants_1.SHARE_DIRECTORY}/${shareId}/${file.id}`).size;
→ 64     await this.prisma.file.create(
Error in connector: Error querying the database: Error code 1: SQL error or missing database
    at In.handleRequestError (/opt/app/backend/node_modules/@prisma/client/runtime/library.js:122:7067)
    at In.handleAndLogRequestError (/opt/app/backend/node_modules/@prisma/client/runtime/library.js:122:6211)
    at In.request (/opt/app/backend/node_modules/@prisma/client/runtime/library.js:122:5919)
    at async l (/opt/app/backend/node_modules/@prisma/client/runtime/library.js:127:11167)
    at async FileService.create (/opt/app/backend/dist/src/file/file.service.js:64:13)
    at async FileController.create (/opt/app/backend/dist/src/file/file.controller.js:30:16)
thread 'tokio-runtime-worker' panicked at libs/user-facing-errors/src/quaint.rs:178:18:
internal error: entered unreachable code
[Nest] 39  - 06/30/2024, 7:16:35 PM   ERROR [ExceptionsHandler]
Invalid `this.prisma.file.create()` invocation in
/opt/app/backend/dist/src/file/file.service.js:64:36

  61 if (isLastChunk) {
  62     fs.renameSync(`${constants_1.SHARE_DIRECTORY}/${shareId}/${file.id}.tmp-chunk`, `${constants_1.SHARE_DIRECTORY}/${shareId}/${file.id}`);
  63     const fileSize = fs.statSync(`${constants_1.SHARE_DIRECTORY}/${shareId}/${file.id}`).size;
→ 64     await this.prisma.file.create(
internal error: entered unreachable code

This is a non-recoverable error which probably happens when the Prisma Query Engine has a panic.

https://github.com/prisma/prisma/issues/new...=bug_report.yml

If you want the Prisma team to look into it, please open the link above 🙏
To increase the chance of success, please post your schema and a snippet of
how you used Prisma Client in the issue.

PrismaClientRustPanicError:
Invalid `this.prisma.file.create()` invocation in
/opt/app/backend/dist/src/file/file.service.js:64:36

  61 if (isLastChunk) {
  62     fs.renameSync(`${constants_1.SHARE_DIRECTORY}/${shareId}/${file.id}.tmp-chunk`, `${constants_1.SHARE_DIRECTORY}/${shareId}/${file.id}`);
  63     const fileSize = fs.statSync(`${constants_1.SHARE_DIRECTORY}/${shareId}/${file.id}`).size;
→ 64     await this.prisma.file.create(
internal error: entered unreachable code

This is a non-recoverable error which probably happens when the Prisma Query Engine has a panic.

https://github.com/prisma/prisma/issues/new...=bug_report.yml

If you want the Prisma team to look into it, please open the link above 🙏
To increase the chance of success, please post your schema and a snippet of
how you used Prisma Client in the issue.

    at In.handleRequestError (/opt/app/backend/node_modules/@prisma/client/runtime/library.js:122:7238)
    at In.handleAndLogRequestError (/opt/app/backend/node_modules/@prisma/client/runtime/library.js:122:6211)
    at In.request (/opt/app/backend/node_modules/@prisma/client/runtime/library.js:122:5919)
    at async l (/opt/app/backend/node_modules/@prisma/client/runtime/library.js:127:11167)
    at async FileService.create (/opt/app/backend/dist/src/file/file.service.js:64:13)
    at async FileController.create (/opt/app/backend/dist/src/file/file.controller.js:30:16)
[Nest] 39  - 06/30/2024, 7:16:35 PM   ERROR [ExceptionsHandler]
Invalid `this.prisma.file.create()` invocation in
/opt/app/backend/dist/src/file/file.service.js:64:36

  61 if (isLastChunk) {
  62     fs.renameSync(`${constants_1.SHARE_DIRECTORY}/${shareId}/${file.id}.tmp-chunk`, `${constants_1.SHARE_DIRECTORY}/${shareId}/${file.id}`);
  63     const fileSize = fs.statSync(`${constants_1.SHARE_DIRECTORY}/${shareId}/${file.id}`).size;
→ 64     await this.prisma.file.create(
Error in connector: Error querying the database: Error code 1: SQL error or missing database
PrismaClientUnknownRequestError:
Invalid `this.prisma.file.create()` invocation in
/opt/app/backend/dist/src/file/file.service.js:64:36

  61 if (isLastChunk) {
  62     fs.renameSync(`${constants_1.SHARE_DIRECTORY}/${shareId}/${file.id}.tmp-chunk`, `${constants_1.SHARE_DIRECTORY}/${shareId}/${file.id}`);
  63     const fileSize = fs.statSync(`${constants_1.SHARE_DIRECTORY}/${shareId}/${file.id}`).size;
→ 64     await this.prisma.file.create(
Error in connector: Error querying the database: Error code 1: SQL error or missing database
    at In.handleRequestError (/opt/app/backend/node_modules/@prisma/client/runtime/library.js:122:7067)
    at In.handleAndLogRequestError (/opt/app/backend/node_modules/@prisma/client/runtime/library.js:122:6211)
    at In.request (/opt/app/backend/node_modules/@prisma/client/runtime/library.js:122:5919)
    at async l (/opt/app/backend/node_modules/@prisma/client/runtime/library.js:127:11167)
    at async FileService.create (/opt/app/backend/dist/src/file/file.service.js:64:13)
    at async FileController.create (/opt/app/backend/dist/src/file/file.controller.js:30:16)
[Nest] 39  - 06/30/2024, 7:16:35 PM   ERROR [ExceptionsHandler]
Invalid `this.prisma.file.create()` invocation in
/opt/app/backend/dist/src/file/file.service.js:64:36

  61 if (isLastChunk) {
  62     fs.renameSync(`${constants_1.SHARE_DIRECTORY}/${shareId}/${file.id}.tmp-chunk`, `${constants_1.SHARE_DIRECTORY}/${shareId}/${file.id}`);
  63     const fileSize = fs.statSync(`${constants_1.SHARE_DIRECTORY}/${shareId}/${file.id}`).size;
→ 64     await this.prisma.file.create(
Error in connector: Error querying the database: Error code 1: SQL error or missing database
PrismaClientUnknownRequestError:
Invalid `this.prisma.file.create()` invocation in
/opt/app/backend/dist/src/file/file.service.js:64:36
```

The log seems to keep repeating the last section.

**Comment by stonith404** [comment]
@kevocl Thanks for your report. I think this is a bug in our ORM Prisma (https://github.com/prisma/prisma/issues/22947). I updated Prisma to the latest version in the `stonith404/pingvin-share:development` image. Could you try if the bug is fixed in the development image?

**Comment by kevocl** [comment]
@stonith404  I've installed the development image and tried uploading a couple of hundred files a few times and that seems to have solved it. Many thanks.

**Comment by stonith404** [comment]
@kevocl Great, thanks for testing. I'll release it ASAP.
