### ISSUE TITLE
🐛 Bug Report: ERROR [ExceptionsHandler] Cannot read properties of undefined (reading 'password')

### ISSUE THREAD

**Issue by droplinxuser** [stonith404/pingvin-share#428]
### 👟 Reproduction steps

Hi,

Thanks for the awesome and neat web app.
It's been working great, without noticeable issues or errors on the frontend.

I'm running via systemd service and nginx, and I have this error log show up on status.

```
● pingvin-back.service - Pingvin Backend
     Loaded: loaded (/etc/systemd/system/pingvin-back.service; enabled; vendor preset: enabled)
     Active: active (running) since Fri 2024-03-22 03:52:27 PST; 19min ago
   Main PID: 2327471 (npm run prod)
      Tasks: 32 (limit: 38231)
     Memory: 105.2M
        CPU: 9.424s
     CGroup: /system.slice/pingvin-back.service
             ├─2327471 "npm run prod" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" ""
             ├─2327516 sh -c "prisma migrate deploy && prisma db seed && node dist/src/main"
             └─2327826 node dist/src/main

Mar 22 04:12:11 hostname npm[2327826]: [Nest] 2327826  - 03/22/2024, 4:12:11 AM   ERROR [ExceptionsHandler] Cannot read properties of undefined (reading 'password')
Mar 22 04:12:11 hostname npm[2327826]: TypeError: Cannot read properties of undefined (reading 'password')
Mar 22 04:12:11 hostname npm[2327826]:     at UserController.getCurrentUser (/pingvin-share/backend/dist/src/user/user.controller.js:32:38)
Mar 22 04:12:11 hostname npm[2327826]:     at /pingvin-share/backend/node_modules/@nestjs/core/router/router-execution-context.js:38:29
Mar 22 04:12:11 hostname npm[2327826]:     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
Mar 22 04:12:12 hostname npm[2327826]: [Nest] 2327826  - 03/22/2024, 4:12:12 AM   ERROR [ExceptionsHandler] Cannot read properties of undefined (reading 'password')
Mar 22 04:12:12 hostname npm[2327826]: TypeError: Cannot read properties of undefined (reading 'password')
Mar 22 04:12:12 hostname npm[2327826]:     at UserController.getCurrentUser (/pingvin-share/backend/dist/src/user/user.controller.js:32:38)
Mar 22 04:12:12 hostname npm[2327826]:     at /pingvin-share/backend/node_modules/@nestjs/core/router/router-execution-context.js:38:29
Mar 22 04:12:12 hostname npm[2327826]:     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

```

### 👍 Expected behavior

I'm hoping there are no error logs when I run:
`systemctl status pingvin-back --no-pager -l`

### 👎 Actual Behavior

See the logs above.

### 🌐 Browser

Doesn't matter and no error on browser.

**Comment by droplinxuser** [comment]
Yes, I have it enabled.

Your welcome :)

**Comment by stonith404** [comment]
Thanks. This should be fixed in the latest development image and will be released in the next release. I won't create an extra release for this bug as this bug doesn't break anything.

**Comment by droplinxuser** [comment]
Thank you so much; it has no more errors now.

```
● pingvin-back.service - Pingvin Backend
     Loaded: loaded (/etc/systemd/system/pingvin-back.service; enabled; vendor preset: enabled)
     Active: active (running) since Tue 2024-03-26 02:20:18 PST; 53s ago
   Main PID: 3467408 (npm run prod)
      Tasks: 32 (limit: 38231)
     Memory: 148.9M
        CPU: 6.946s
     CGroup: /system.slice/pingvin-back.service
             ├─3467408 "npm run prod" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" ""
             ├─3467434 sh -c "prisma migrate deploy && prisma db seed && node dist/src/main"
             └─3467744 node dist/src/main

Mar 26 02:20:23 hostname npm[3467744]: [Nest] 3467744  - 03/26/2024, 2:20:23 AM     LOG [RouterExplorer] Mapped {/api/users/:id, PATCH} route +0ms
Mar 26 02:20:23 hostname npm[3467744]: [Nest] 3467744  - 03/26/2024, 2:20:23 AM     LOG [RouterExplorer] Mapped {/api/users/:id, DELETE} route +0ms
Mar 26 02:20:23 hostname npm[3467744]: [Nest] 3467744  - 03/26/2024, 2:20:23 AM     LOG [RoutesResolver] OAuthController {/api/oauth}: +0ms
Mar 26 02:20:23 hostname npm[3467744]: [Nest] 3467744  - 03/26/2024, 2:20:23 AM     LOG [RouterExplorer] Mapped {/api/oauth/available, GET} route +0ms
Mar 26 02:20:23 hostname npm[3467744]: [Nest] 3467744  - 03/26/2024, 2:20:23 AM     LOG [RouterExplorer] Mapped {/api/oauth/status, GET} route +1ms
Mar 26 02:20:23 hostname npm[3467744]: [Nest] 3467744  - 03/26/2024, 2:20:23 AM     LOG [RouterExplorer] Mapped {/api/oauth/auth/:provider, GET} route +0ms
Mar 26 02:20:23 hostname npm[3467744]: [Nest] 3467744  - 03/26/2024, 2:20:23 AM     LOG [RouterExplorer] Mapped {/api/oauth/callback/:provider, GET} route +0ms
Mar 26 02:20:23 hostname npm[3467744]: [Nest] 3467744  - 03/26/2024, 2:20:23 AM     LOG [RouterExplorer] Mapped {/api/oauth/unlink/:provider, POST} route +0ms
Mar 26 02:20:23 hostname npm[3467744]: [Nest] 3467744  - 03/26/2024, 2:20:23 AM     LOG [NestApplication] Nest application successfully started +18ms
Mar 26 02:20:23 hostname npm[3467744]: [Nest] 3467744  - 03/26/2024, 2:20:23 AM     LOG [ClamScanService] ClamAV is not active
```
