### ISSUE TITLE
🐛 Bug Report: 500 (Internal Server Error) when using the "Name" field

### ISSUE THREAD

**Issue by droplinxuser** [stonith404/pingvin-share#466]
### 👟 Reproduction steps

- Update to version 0.24.1
- Visit /upload page to upload a file
- On "Name" field, put any title
<img width="190" alt="image" src="https://github.com/stonith404/pingvin-share/assets/68084306/80807120-daf7-49e9-9cb4-34b928449864">

- Then press "Share"
- It will fail with this error on browser console:
500 (Internal Server Error)

<img width="432" alt="image" src="https://github.com/stonith404/pingvin-share/assets/68084306/b1daec01-bfb5-472d-9622-60dde82dfa15">

### 👍 Expected behavior

The upload will succeed.

### 👎 Actual Behavior

500 (Internal Server Error)

### 🌐 Browser

Chrome latest on MacOS

**Comment by droplinxuser** [comment]
```
May 04 21:28:57 npm[22337]: Unknown argument `name`. Available options are listed in green.
May 04 21:28:57 npm[22337]:     at Ur (/var/www/pingvin_source/backend/node_modules/@prisma/client/runtime/library.js:115:5803)
May 04 21:28:57 npm[22337]:     at zr.handleRequestError (/var/www/pingvin_source/backend/node_modules/@prisma/client/runtime/library.js:122:8007)
May 04 21:28:57 npm[22337]:     at zr.handleAndLogRequestError (/var/www/pingvin_source/backend/node_modules/@prisma/client/runtime/library.js:122:7697)
May 04 21:28:57 npm[22337]:     at zr.request (/var/www/pingvin_source/backend/node_modules/@prisma/client/runtime/library.js:122:7307)
May 04 21:28:57 npm[22337]:     at async ShareService.create (/var/www/pingvin_source/backend/dist/src/share/share.service.js:66:28)
May 04 21:28:57 npm[22337]:     at async ShareController.create (/var/www/pingvin_source/backend/dist/src/share/share.controller.js:54:48)
May 04 21:37:21 npm[22337]: [Nest] 22337  - 05/04/2024, 9:37:21 PM   ERROR [ExceptionsHandler] 
May 04 21:37:21 npm[22337]: Invalid `this.prisma.share.create()` invocation in
May 04 21:37:21 npm[22337]: /var/www/pingvin_source/backend/dist/src/share/share.service.js:66:52
May 04 21:37:21 npm[22337]:   63 fs.mkdirSync(`${constants_1.SHARE_DIRECTORY}/${share.id}`, {
May 04 21:37:21 npm[22337]:   64     recursive: true,
May 04 21:37:21 npm[22337]:   65 });
May 04 21:37:21 npm[22337]: → 66 const shareTuple = await this.prisma.share.create({
May 04 21:37:21 npm[22337]:        data: {
May 04 21:37:21 npm[22337]:          id: "cwNzk1M",
May 04 21:37:21 npm[22337]:          name: "test",
May 04 21:37:21 npm[22337]:          ~~~~
May 04 21:37:21 npm[22337]:          expiration: new Date("2024-05-05T13:37:21.403Z"),
May 04 21:37:21 npm[22337]:          recipients: {
May 04 21:37:21 npm[22337]:            create: []
May 04 21:37:21 npm[22337]:          },
May 04 21:37:21 npm[22337]:          security: {
May 04 21:37:21 npm[22337]:            create: undefined
May 04 21:37:21 npm[22337]:          },
May 04 21:37:21 npm[22337]:          creator: {
May 04 21:37:21 npm[22337]:            connect: {
May 04 21:37:21 npm[22337]:              id: "0e49e8b4-faaf-4e0b-960a-eec12a87ebf5"
May 04 21:37:21 npm[22337]:            }
May 04 21:37:21 npm[22337]:          },
May 04 21:37:21 npm[22337]:      ?   createdAt?: DateTime,
May 04 21:37:21 npm[22337]:      ?   uploadLocked?: Boolean,
May 04 21:37:21 npm[22337]:      ?   isZipReady?: Boolean,
May 04 21:37:21 npm[22337]:      ?   views?: Int,
May 04 21:37:21 npm[22337]:      ?   description?: String | Null,
May 04 21:37:21 npm[22337]:      ?   removedReason?: String | Null,
May 04 21:37:21 npm[22337]:      ?   reverseShare?: ReverseShareCreateNestedOneWithoutSharesInput,
May 04 21:37:21 npm[22337]:      ?   files?: FileCreateNestedManyWithoutShareInput
May 04 21:37:21 npm[22337]:        }
May 04 21:37:21 npm[22337]:      })
May 04 21:37:21 npm[22337]: Unknown argument `name`. Available options are listed in green.
May 04 21:37:21 npm[22337]: PrismaClientValidationError:
May 04 21:37:21 npm[22337]: Invalid `this.prisma.share.create()` invocation in
May 04 21:37:21 npm[22337]: /var/www/pingvin_source/backend/dist/src/share/share.service.js:66:52
May 04 21:37:21 npm[22337]:   63 fs.mkdirSync(`${constants_1.SHARE_DIRECTORY}/${share.id}`, {
May 04 21:37:21 npm[22337]:   64     recursive: true,
May 04 21:37:21 npm[22337]:   65 });
May 04 21:37:21 npm[22337]: → 66 const shareTuple = await this.prisma.share.create({
May 04 21:37:21 npm[22337]:        data: {
May 04 21:37:21 npm[22337]:          id: "cwNzk1M",
May 04 21:37:21 npm[22337]:          name: "test",
May 04 21:37:21 npm[22337]:          ~~~~
May 04 21:37:21 npm[22337]:          expiration: new Date("2024-05-05T13:37:21.403Z"),
May 04 21:37:21 npm[22337]:          recipients: {
May 04 21:37:21 npm[22337]:            create: []
May 04 21:37:21 npm[22337]:          },
May 04 21:37:21 npm[22337]:          security: {
May 04 21:37:21 npm[22337]:            create: undefined
May 04 21:37:21 npm[22337]:          },
May 04 21:37:21 npm[22337]:          creator: {
May 04 21:37:21 npm[22337]:            connect: {
May 04 21:37:21 npm[22337]:              id: "0e49e8b4-faaf-4e0b-960a-eec12a87ebf5"
May 04 21:37:21 npm[22337]:            }
May 04 21:37:21 npm[22337]:          },
May 04 21:37:21 npm[22337]:      ?   createdAt?: DateTime,
May 04 21:37:21 npm[22337]:      ?   uploadLocked?: Boolean,
May 04 21:37:21 npm[22337]:      ?   isZipReady?: Boolean,
May 04 21:37:21 npm[22337]:      ?   views?: Int,
May 04 21:37:21 npm[22337]:      ?   description?: String | Null,
May 04 21:37:21 npm[22337]:      ?   removedReason?: String | Null,
May 04 21:37:21 npm[22337]:      ?   reverseShare?: ReverseShareCreateNestedOneWithoutSharesInput,
May 04 21:37:21 npm[22337]:      ?   files?: FileCreateNestedManyWithoutShareInput
May 04 21:37:21 npm[22337]:        }
May 04 21:37:21 npm[22337]:      })
May 04 21:37:21 npm[22337]: Unknown argument `name`. Available options are listed in green.
May 04 21:37:21 npm[22337]:     at Ur (/var/www/pingvin_source/backend/node_modules/@prisma/client/runtime/library.js:115:5803)
May 04 21:37:21 npm[22337]:     at zr.handleRequestError (/var/www/pingvin_source/backend/node_modules/@prisma/client/runtime/library.js:122:8007)
May 04 21:37:21 npm[22337]:     at zr.handleAndLogRequestError (/var/www/pingvin_source/backend/node_modules/@prisma/client/runtime/library.js:122:7697)
May 04 21:37:21 npm[22337]:     at zr.request (/var/www/pingvin_source/backend/node_modules/@prisma/client/runtime/library.js:122:7307)
May 04 21:37:21 npm[22337]:     at async ShareService.create (/var/www/pingvin_source/backend/dist/src/share/share.service.js:66:28)
May 04 21:37:21 npm[22337]:     at async ShareController.create (/var/www/pingvin_source/backend/dist/src/share/share.controller.js:54:48)
```

**Comment by stonith404** [comment]
Which command do you use to start the backend?

**Comment by droplinxuser** [comment]
This command:
```
WorkingDirectory=/var/www/pingvin_source/backend
ExecStart=/usr/bin/npm -- run prod
```

Am I doing it wrong?

**Comment by droplinxuser** [comment]
SystemD Status:

```
# systemctl status pingvin-back --no-pager -l
● pingvin-back.service - Pingvin Backend
     Loaded: loaded (/etc/systemd/system/pingvin-back.service; enabled; vendor preset: enabled)
     Active: active (running) since Sat 2024-05-04 20:10:26 PST; 4h 5min ago
   Main PID: 22206 (npm run prod)
      Tasks: 32 (limit: 38230)
     Memory: 3.9G
        CPU: 1min 27.113s
     CGroup: /system.slice/pingvin-back.service
             ├─22206 "npm run prod" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" ""
             ├─22231 sh -c "prisma migrate deploy && prisma db seed && node dist/src/main"
             └─22337 node dist/src/main
```

**Comment by stonith404** [comment]
Thanks. That's strange, somehow the database migration didn't run. Can you try to run the command `prisma migrate deploy` inside the `backend` folder manually?

**Comment by droplinxuser** [comment]
I got: prisma: command not found

**Comment by droplinxuser** [comment]
I manually installed prisma with this command:
`npm install -g prisma`

Now I have:
```
Error: Could not find a schema.prisma file that is required for this command.
You can either provide it with --schema, set it as `prisma.schema` in your package.json or put it into the default location ./prisma/schema.prisma https://pris.ly/d/prisma-schema-location
```

**Comment by droplinxuser** [comment]
I have this set in pingvin_source/backend/prisma/.env
```
DATABASE_URL="file:/var/www/pingvin_data/pingvin-share.db?connection_limit=1"
DATA_DIRECTORY="/var/www/pingvin_data"
```

Does it relate to the error?

**Comment by droplinxuser** [comment]
If I run:

```
cd /var/www/pingvin_source/ &&\
systemctl stop pingvin-back ;\
git reset --hard &&\
git pull &&\
cd /var/www/pingvin_source/backend &&\
npm install &&\
npm run build &&\
prisma migrate deploy ;\ 
prisma db seed ;\
systemctl start pingvin-back

```

I got:
```
> pingvin-share-backend@0.24.1 build
> nest build

Environment variables loaded from prisma/.env
Prisma schema loaded from prisma/schema.prisma
Datasource "db": SQLite database "pingvin-share.db" at "file:/var/www/pingvin_data/pingvin-share.db?connection_limit=1"

18 migrations found in prisma/migrations


No pending migrations to apply.
 : command not found

root@/var/www/pingvin_source/backend# prisma db seed ;\
> systemctl start pingvin-back
Environment variables loaded from prisma/.env
Running seed command `ts-node prisma/seed/config.seed.ts` ...

An error occurred while running the seed command:
Error: Command failed with ENOENT: ts-node prisma/seed/config.seed.ts
spawn ts-node ENOENT
```

**Comment by droplinxuser** [comment]
I install ts-node with:
`npm install -g ts-node`

Now I have this:
```
> pingvin-share-backend@0.24.1 build
> nest build

Environment variables loaded from prisma/.env
Prisma schema loaded from prisma/schema.prisma
Datasource "db": SQLite database "pingvin-share.db" at "file:/var/www/pingvin_data/pingvin-share.db?connection_limit=1"

18 migrations found in prisma/migrations


No pending migrations to apply.
 : command not found

root@/var/www/pingvin_source/backend# prisma db seed ;\
> systemctl start pingvin-back
Environment variables loaded from prisma/.env
Running seed command `ts-node prisma/seed/config.seed.ts` ...

🌱  The seed command has been executed.
```

**Comment by droplinxuser** [comment]
I still this error on browser console only when I set a name on the upload file:
<img width="432" alt="image" src="https://github.com/stonith404/pingvin-share/assets/68084306/bf85f0b4-a862-4c8a-a05b-918a362e9fb1">

Even though this command has succeeded without errors now:
```
cd /var/www/pingvin_source/backend &&\
npm install &&\
npm run build &&\
prisma migrate deploy ;\ 
prisma db seed ;\
systemctl start pingvin-back
```

**Comment by stonith404** [comment]
Yeah, everything looks fine. Also, Pingvin Share thinks the migration has been executed. Can you try manually adding the `name` property to the table `Share`?

You need to install the [SQLite CLI](https://sqlite.org/cli.html) and run
```
sqlite3 /var/www/pingvin_data/pingvin-share.db "ALTER TABLE Share ADD COLUMN name TEXT;"
```

**Comment by droplinxuser** [comment]
It's in there already?

```
# sqlite3 /var/www/pingvin_data/pingvin-share.db "ALTER TABLE Share ADD COLUMN name TEXT;"
Error: in prepare, duplicate column name: name (1)

```

**Comment by droplinxuser** [comment]
Latest log:

```
npm[52882]: [Nest] 52882  - 05/06/2024, 10:54:47 PM   ERROR [ExceptionsHandler] 
npm[52882]: Invalid `this.prisma.share.create()` invocation in
npm[52882]: /var/www/pingvin_source/backend/dist/src/share/share.service.js:66:52
npm[52882]:   63 fs.mkdirSync(`${constants_1.SHARE_DIRECTORY}/${share.id}`, {
npm[52882]:   64     recursive: true,
npm[52882]:   65 });
npm[52882]: → 66 const shareTuple = await this.prisma.share.create({
npm[52882]:        data: {
npm[52882]:          id: "UxMDc5N",
npm[52882]:          name: "werrr",
npm[52882]:          ~~~~
npm[52882]:          expiration: new Date("2024-05-07T14:54:47.778Z"),
npm[52882]:          recipients: {
npm[52882]:            create: []
npm[52882]:          },
npm[52882]:          security: {
npm[52882]:            create: undefined
npm[52882]:          },
npm[52882]:          creator: {
npm[52882]:            connect: undefined
npm[52882]:          },
npm[52882]:      ?   createdAt?: DateTime,
npm[52882]:      ?   uploadLocked?: Boolean,
npm[52882]:      ?   isZipReady?: Boolean,
npm[52882]:      ?   views?: Int,
npm[52882]:      ?   description?: String | Null,
npm[52882]:      ?   removedReason?: String | Null,
npm[52882]:      ?   reverseShare?: ReverseShareCreateNestedOneWithoutSharesInput,
npm[52882]:      ?   files?: FileCreateNestedManyWithoutShareInput
npm[52882]:        }
npm[52882]:      })
npm[52882]: Unknown argument `name`. Available options are listed in green.
npm[52882]: PrismaClientValidationError:
npm[52882]: Invalid `this.prisma.share.create()` invocation in
npm[52882]: /var/www/pingvin_source/backend/dist/src/share/share.service.js:66:52
npm[52882]:   63 fs.mkdirSync(`${constants_1.SHARE_DIRECTORY}/${share.id}`, {
npm[52882]:   64     recursive: true,
npm[52882]:   65 });
npm[52882]: → 66 const shareTuple = await this.prisma.share.create({
npm[52882]:        data: {
npm[52882]:          id: "UxMDc5N",
npm[52882]:          name: "werrr",
npm[52882]:          ~~~~
npm[52882]:          expiration: new Date("2024-05-07T14:54:47.778Z"),
npm[52882]:          recipients: {
npm[52882]:            create: []
npm[52882]:          },
npm[52882]:          security: {
npm[52882]:            create: undefined
npm[52882]:          },
npm[52882]:          creator: {
npm[52882]:            connect: undefined
npm[52882]:          },
npm[52882]:      ?   createdAt?: DateTime,
npm[52882]:      ?   uploadLocked?: Boolean,
npm[52882]:      ?   isZipReady?: Boolean,
npm[52882]:      ?   views?: Int,
npm[52882]:      ?   description?: String | Null,
npm[52882]:      ?   removedReason?: String | Null,
npm[52882]:      ?   reverseShare?: ReverseShareCreateNestedOneWithoutSharesInput,
npm[52882]:      ?   files?: FileCreateNestedManyWithoutShareInput
npm[52882]:        }
npm[52882]:      })
npm[52882]: Unknown argument `name`. Available options are listed in green.
npm[52882]:     at Ur (/var/www/pingvin_source/backend/node_modules/@prisma/client/runtime/library.js:115:5803)
npm[52882]:     at zr.handleRequestError (/var/www/pingvin_source/backend/node_modules/@prisma/client/runtime/library.js:122:8007)
npm[52882]:     at zr.handleAndLogRequestError (/var/www/pingvin_source/backend/node_modules/@prisma/client/runtime/library.js:122:7697)
npm[52882]:     at zr.request (/var/www/pingvin_source/backend/node_modules/@prisma/client/runtime/library.js:122:7307)
npm[52882]:     at async ShareService.create (/var/www/pingvin_source/backend/dist/src/share/share.service.js:66:28)
npm[52882]:     at async ShareController.create (/var/www/pingvin_source/backend/dist/src/share/share.controller.js:54:48)
```

**Comment by stonith404** [comment]
That's really strange, yeah the property is already in the database. I'm not sure what the issue could be. Interestingly, it appears that you're the only one experiencing this bug, as we've received no other reports. My final recommendation would be to execute `npx prisma generate` within the source folder. Should this fail to resolve the issue, your best course of action might be to perform a fresh installation. If possible, I would suggest using Docker for the installation, as it typically encounters fewer errors.

**Comment by droplinxuser** [comment]
Run: `npx prisma generate`

Inside /var/www/pingvin_source/backend/?

Unfortunately, I cannot perform a fresh install as it has lots of files already uploaded.
I cannot and intentionally avoid Docker as I have several other apps on the same server, like PHP-based websites.

Thanks for the response.

**Comment by droplinxuser** [comment]
I moved server, updated nodejs and it's working as expected now.
Thanks for the great support as always :)
