### ISSUE TITLE
🐛 Bug Report: Authentik login not working

### ISSUE THREAD

**Issue by sahara101** [stonith404/pingvin-share#551]
### 👟 Reproduction steps

Try to log in with Authentik

### 👍 Expected behavior

OIDC working

### 👎 Actual Behavior

{"statusCode":500,"message":"Internal server error"}

[Nest] 38  - 08/02/2024, 9:58:10 AM   ERROR [ExceptionsHandler] fetch failed
TypeError: fetch failed
    at node:internal/deps/undici/undici:13178:13
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async OidcProvider.fetchConfiguration (/opt/app/backend/dist/src/oauth/provider/genericOidc.provider.js:134:21)
    at async OidcProvider.getConfiguration (/opt/app/backend/dist/src/oauth/provider/genericOidc.provider.js:29:13)
    at async OidcProvider.getAuthEndpoint (/opt/app/backend/dist/src/oauth/provider/genericOidc.provider.js:40:31)
    at async OAuthController.auth (/opt/app/backend/dist/src/oauth/oauth.controller.js:44:21)

It worked a couple of days ago and now all of a sudden it does not work anymore. The funny part is, I deactivated pssword login :D

### 🌐 Browser

Safari, Chrome

**Comment by sahara101** [comment]
Forgot to mention, I had before updated Authentik to latest version

**Comment by stonith404** [comment]
Does Authentik still work with other applications? What happens if you run the following command?
```
docker compose exec pingvin-share curl http://your-authentik-domain
```

**Comment by sahara101** [comment]
Yes it worked with others. But...it started working again on its own. No idea what happened.

**Comment by stonith404** [comment]
Okay strange, I'll close this issue then. Feel free to comment if the issue occurs again.

**Comment by sahara101** [comment]
Wanted just to get back with update. The curl command helped a lot. I added to traefik a macvlan IP besides the normal docker network. Seems pingvin container cannot connect to any traefik enabed sites. So I just added the macvlan (without any IP) network to pingvin as well and it started working.
