### ISSUE TITLE
🐛 Bug Report: ERROR [ExceptionsHandler] request aborted

### ISSUE THREAD

**Issue by Destinyg133** [stonith404/pingvin-share#697]
### 👟 Reproduction steps

just upload

### 👍 Expected behavior

upload all files

### 👎 Actual Behavior

failed on last 3

### 📜 Logs

BadRequestError: request aborted
    at IncomingMessage.onAborted (/opt/app/backend/node_modules/raw-body/index.js:245:10)
    at IncomingMessage.emit (node:events:519:28)
    at IncomingMessage._destroy (node:_http_incoming:221:10)
    at _destroy (node:internal/streams/destroy:121:10)
    at IncomingMessage.destroy (node:internal/streams/destroy:83:5)
    at abortIncoming (node:_http_server:796:9)
    at socketOnClose (node:_http_server:790:3)
    at Socket.emit (node:events:531:35)
    at TCP.<anonymous> (node:net:339:12)
[Nest] 50  - 12/08/2024, 12:38:28 AM   ERROR [ExceptionsHandler] request aborted
BadRequestError: request aborted
    at IncomingMessage.onAborted (/opt/app/backend/node_modules/raw-body/index.js:245:10)
    at IncomingMessage.emit (node:events:519:28)
    at IncomingMessage._destroy (node:_http_incoming:221:10)
    at _destroy (node:internal/streams/destroy:121:10)
    at IncomingMessage.destroy (node:internal/streams/destroy:83:5)
    at abortIncoming (node:_http_server:796:9)
    at socketOnClose (node:_http_server:790:3)
    at Socket.emit (node:events:531:35)
    at TCP.<anonymous> (node:net:339:12)
[Nest] 50  - 12/08/2024, 12:38:33 AM   ERROR [ExceptionsHandler] request aborted
BadRequestError: request aborted
    at IncomingMessage.onAborted (/opt/app/backend/node_modules/raw-body/index.js:245:10)
    at IncomingMessage.emit (node:events:519:28)
    at IncomingMessage._destroy (node:_http_incoming:221:10)
    at _destroy (node:internal/streams/destroy:121:10)
    at IncomingMessage.destroy (node:internal/streams/destroy:83:5)
    at abortIncoming (node:_http_server:796:9)
    at socketOnClose (node:_http_server:790:3)
    at Socket.emit (node:events:531:35)
    at TCP.<anonymous> (node:net:339:12)
[Nest] 50  - 12/08/2024, 12:38:33 AM   ERROR [ExceptionsHandler] request aborted
BadRequestError: request aborted
    at IncomingMessage.onAborted (/opt/app/backend/node_modules/raw-body/index.js:245:10)
    at IncomingMessage.emit (node:events:519:28)
    at IncomingMessage._destroy (node:_http_incoming:221:10)
    at _destroy (node:internal/streams/destroy:121:10)
    at IncomingMessage.destroy (node:internal/streams/destroy:83:5)
    at abortIncoming (node:_http_server:796:9)
    at socketOnClose (node:_http_server:790:3)
    at Socket.emit (node:events:531:35)
    at TCP.<anonymous> (node:net:339:12)
[Nest] 50  - 12/08/2024, 12:38:33 AM   ERROR [ExceptionsHandler] request aborted
BadRequestError: request aborted
    at IncomingMessage.onAborted (/opt/app/backend/node_modules/raw-body/index.js:245:10)
    at IncomingMessage.emit (node:events:519:28)
    at IncomingMessage._destroy (node:_http_incoming:221:10)
    at _destroy (node:internal/streams/destroy:121:10)
    at IncomingMessage.destroy (node:internal/streams/destroy:83:5)
    at abortIncoming (node:_http_server:796:9)
    at socketOnClose (node:_http_server:790:3)
    at Socket.emit (node:events:531:35)
    at TCP.<anonymous> (node:net:339:12)
[Nest] 50  - 12/08/2024, 12:38:39 AM   ERROR [ExceptionsHandler] request aborted
BadRequestError: request aborted
    at IncomingMessage.onAborted (/opt/app/backend/node_modules/raw-body/index.js:245:10)
    at IncomingMessage.emit (node:events:519:28)
    at IncomingMessage._destroy (node:_http_incoming:221:10)
    at _destroy (node:internal/streams/destroy:121:10)
    at IncomingMessage.destroy (node:internal/streams/destroy:83:5)
    at abortIncoming (node:_http_server:796:9)
    at socketOnClose (node:_http_server:790:3)
    at Socket.emit (node:events:531:35)
    at TCP.<anonymous> (node:net:339:12)
[Nest] 50  - 12/08/2024, 12:38:39 AM   ERROR [ExceptionsHandler] request aborted
BadRequestError: request aborted
    at IncomingMessage.onAborted (/opt/app/backend/node_modules/raw-body/index.js:245:10)
    at IncomingMessage.emit (node:events:519:28)
    at IncomingMessage._destroy (node:_http_incoming:221:10)
    at _destroy (node:internal/streams/destroy:121:10)
    at IncomingMessage.destroy (node:internal/streams/destroy:83:5)
    at abortIncoming (node:_http_server:796:9)
    at socketOnClose (node:_http_server:790:3)
    at Socket.emit (node:events:531:35)
    at TCP.<anonymous> (node:net:339:12)
[Nest] 50  - 12/08/2024, 12:38:39 AM   ERROR [ExceptionsHandler] request aborted
BadRequestError: request aborted
    at IncomingMessage.onAborted (/opt/app/backend/node_modules/raw-body/index.js:245:10)
    at IncomingMessage.emit (node:events:519:28)
    at IncomingMessage._destroy (node:_http_incoming:221:10)
    at _destroy (node:internal/streams/destroy:121:10)
    at IncomingMessage.destroy (node:internal/streams/destroy:83:5)
    at abortIncoming (node:_http_server:796:9)
    at socketOnClose (node:_http_server:790:3)
    at Socket.emit (node:events:531:35)
    at TCP.<anonymous> (node:net:339:12)
[Nest] 50  - 12/08/2024, 12:38:44 AM   ERROR [ExceptionsHandler] request aborted
BadRequestError: request aborted
    at IncomingMessage.onAborted (/opt/app/backend/node_modules/raw-body/index.js:245:10)
    at IncomingMessage.emit (node:events:519:28)
    at IncomingMessage._destroy (node:_http_incoming:221:10)
    at _destroy (node:internal/streams/destroy:121:10)
    at IncomingMessage.destroy (node:internal/streams/destroy:83:5)
    at abortIncoming (node:_http_server:796:9)
    at socketOnClose (node:_http_server:790:3)
    at Socket.emit (node:events:531:35)
    at TCP.<anonymous> (node:net:339:12)
[Nest] 50  - 12/08/2024, 12:38:44 AM   ERROR [ExceptionsHandler] request aborted
BadRequestError: request aborted
    at IncomingMessage.onAborted (/opt/app/backend/node_modules/raw-body/index.js:245:10)
    at IncomingMessage.emit (node:events:519:28)
    at IncomingMessage._destroy (node:_http_incoming:221:10)
    at _destroy (node:internal/streams/destroy:121:10)
    at IncomingMessage.destroy (node:internal/streams/destroy:83:5)
    at abortIncoming (node:_http_server:796:9)
    at socketOnClose (node:_http_server:790:3)
    at Socket.emit (node:events:531:35)
    at TCP.<anonymous> (node:net:339:12)
[Nest] 50  - 12/08/2024, 12:38:44 AM   ERROR [ExceptionsHandler] request aborted
BadRequestError: request aborted
    at IncomingMessage.onAborted (/opt/app/backend/node_modules/raw-body/index.js:245:10)
    at IncomingMessage.emit (node:events:519:28)
    at IncomingMessage._destroy (node:_http_incoming:221:10)
    at _destroy (node:internal/streams/destroy:121:10)
    at IncomingMessage.destroy (node:internal/streams/destroy:83:5)
    at abortIncoming (node:_http_server:796:9)
    at socketOnClose (node:_http_server:790:3)
    at Socket.emit (node:events:531:35)
    at TCP.<anonymous> (node:net:339:12)
[Nest] 50  - 12/08/2024, 12:38:50 AM   ERROR [ExceptionsHandler] request aborted
BadRequestError: request aborted
    at IncomingMessage.onAborted (/opt/app/backend/node_modules/raw-body/index.js:245:10)
    at IncomingMessage.emit (node:events:519:28)
    at IncomingMessage._destroy (node:_http_incoming:221:10)
    at _destroy (node:internal/streams/destroy:121:10)
    at IncomingMessage.destroy (node:internal/streams/destroy:83:5)
    at abortIncoming (node:_http_server:796:9)
    at socketOnClose (node:_http_server:790:3)
    at Socket.emit (node:events:531:35)
    at TCP.<anonymous> (node:net:339:12)
[Nest] 50  - 12/08/2024, 12:38:50 AM   ERROR [ExceptionsHandler] request aborted
BadRequestError: request aborted
    at IncomingMessage.onAborted (/opt/app/backend/node_modules/raw-body/index.js:245:10)
    at IncomingMessage.emit (node:events:519:28)
    at IncomingMessage._destroy (node:_http_incoming:221:10)
    at _destroy (node:internal/streams/destroy:121:10)
    at IncomingMessage.destroy (node:internal/streams/destroy:83:5)
    at abortIncoming (node:_http_server:796:9)
    at socketOnClose (node:_http_server:790:3)
    at Socket.emit (node:events:531:35)
    at TCP.<anonymous> (node:net:339:12)
[Nest] 50  - 12/08/2024, 12:38:55 AM   ERROR [ExceptionsHandler] request aborted
BadRequestError: request aborted
    at IncomingMessage.onAborted (/opt/app/backend/node_modules/raw-body/index.js:245:10)
    at IncomingMessage.emit (node:events:519:28)
    at IncomingMessage._destroy (node:_http_incoming:221:10)
    at _destroy (node:internal/streams/destroy:121:10)
    at IncomingMessage.destroy (node:internal/streams/destroy:83:5)
    at abortIncoming (node:_http_server:796:9)
    at socketOnClose (node:_http_server:790:3)
    at Socket.emit (node:events:531:35)
    at TCP.<anonymous> (node:net:339:12)
[Nest] 50  - 12/08/2024, 12:38:55 AM   ERROR [ExceptionsHandler] request aborted
BadRequestError: request aborted
    at IncomingMessage.onAborted (/opt/app/backend/node_modules/raw-body/index.js:245:10)
    at IncomingMessage.emit (node:events:519:28)
    at IncomingMessage._destroy (node:_http_incoming:221:10)
    at _destroy (node:internal/streams/destroy:121:10)
    at IncomingMessage.destroy (node:internal/streams/destroy:83:5)
    at abortIncoming (node:_http_server:796:9)
    at socketOnClose (node:_http_server:790:3)
    at Socket.emit (node:events:531:35)
    at TCP.<anonymous> (node:net:339:12)
[Nest] 50  - 12/08/2024, 12:39:01 AM   ERROR [ExceptionsHandler] request aborted
BadRequestError: request aborted
    at IncomingMessage.onAborted (/opt/app/backend/node_modules/raw-body/index.js:245:10)
    at IncomingMessage.emit (node:events:519:28)
    at IncomingMessage._destroy (node:_http_incoming:221:10)
    at _destroy (node:internal/streams/destroy:121:10)
    at IncomingMessage.destroy (node:internal/streams/destroy:83:5)
    at abortIncoming (node:_http_server:796:9)
    at socketOnClose (node:_http_server:790:3)
    at Socket.emit (node:events:531:35)
    at TCP.<anonymous> (node:net:339:12)
[Nest] 50  - 12/08/2024, 12:39:01 AM   ERROR [ExceptionsHandler] request aborted
BadRequestError: request aborted
    at IncomingMessage.onAborted (/opt/app/backend/node_modules/raw-body/index.js:245:10)
    at IncomingMessage.emit (node:events:519:28)
    at IncomingMessage._destroy (node:_http_incoming:221:10)
    at _destroy (node:internal/streams/destroy:121:10)
    at IncomingMessage.destroy (node:internal/streams/destroy:83:5)
    at abortIncoming (node:_http_server:796:9)
    at socketOnClose (node:_http_server:790:3)
    at Socket.emit (node:events:531:35)
    at TCP.<anonymous> (node:net:339:12)
[Nest] 50  - 12/08/2024, 12:39:06 AM   ERROR [ExceptionsHandler] request aborted
BadRequestError: request aborted
    at IncomingMessage.onAborted (/opt/app/backend/node_modules/raw-body/index.js:245:10)
    at IncomingMessage.emit (node:events:519:28)
    at IncomingMessage._destroy (node:_http_incoming:221:10)
    at _destroy (node:internal/streams/destroy:121:10)
    at IncomingMessage.destroy (node:internal/streams/destroy:83:5)
    at abortIncoming (node:_http_server:796:9)
    at socketOnClose (node:_http_server:790:3)
    at Socket.emit (node:events:531:35)
    at TCP.<anonymous> (node:net:339:12)
[Nest] 50  - 12/08/2024, 12:39:06 AM   ERROR [ExceptionsHandler] request aborted
BadRequestError: request aborted
    at IncomingMessage.onAborted (/opt/app/backend/node_modules/raw-body/index.js:245:10)
    at IncomingMessage.emit (node:events:519:28)
    at IncomingMessage._destroy (node:_http_incoming:221:10)
    at _destroy (node:internal/streams/destroy:121:10)
    at IncomingMessage.destroy (node:internal/streams/destroy:83:5)
    at abortIncoming (node:_http_server:796:9)
    at socketOnClose (node:_http_server:790:3)
    at Socket.emit (node:events:531:35)
    at TCP.<anonymous> (node:net:339:12)
[Nest] 50  - 12/08/2024, 12:39:06 AM   ERROR [ExceptionsHandler] request aborted
BadRequestError: request aborted
    at IncomingMessage.onAborted (/opt/app/backend/node_modules/raw-body/index.js:245:10)
    at IncomingMessage.emit (node:events:519:28)
    at IncomingMessage._destroy (node:_http_incoming:221:10)
    at _destroy (node:internal/streams/destroy:121:10)
    at IncomingMessage.destroy (node:internal/streams/destroy:83:5)
    at abortIncoming (node:_http_server:796:9)
    at socketOnClose (node:_http_server:790:3)
    at Socket.emit (node:events:531:35)
    at TCP.<anonymous> (node:net:339:12)
[Nest] 50  - 12/08/2024, 12:39:12 AM   ERROR [ExceptionsHandler] request aborted
BadRequestError: request aborted
    at IncomingMessage.onAborted (/opt/app/backend/node_modules/raw-body/index.js:245:10)
    at IncomingMessage.emit (node:events:519:28)
    at IncomingMessage._destroy (node:_http_incoming:221:10)
    at _destroy (node:internal/streams/destroy:121:10)
    at IncomingMessage.destroy (node:internal/streams/destroy:83:5)
    at abortIncoming (node:_http_server:796:9)
    at socketOnClose (node:_http_server:790:3)
    at Socket.emit (node:events:531:35)
    at TCP.<anonymous> (node:net:339:12)
[Nest] 50  - 12/08/2024, 12:39:12 AM   ERROR [ExceptionsHandler] request aborted
BadRequestError: request aborted
    at IncomingMessage.onAborted (/opt/app/backend/node_modules/raw-body/index.js:245:10)
    at IncomingMessage.emit (node:events:519:28)
    at IncomingMessage._destroy (node:_http_incoming:221:10)
    at _destroy (node:internal/streams/destroy:121:10)
    at IncomingMessage.destroy (node:internal/streams/destroy:83:5)
    at abortIncoming (node:_http_server:796:9)
    at socketOnClose (node:_http_server:790:3)
    at Socket.emit (node:events:531:35)
    at TCP.<anonymous> (node:net:339:12)
[Nest] 50  - 12/08/2024, 12:39:12 AM   ERROR [ExceptionsHandler] request aborted
BadRequestError: request aborted
    at IncomingMessage.onAborted (/opt/app/backend/node_modules/raw-body/index.js:245:10)
    at IncomingMessage.emit (node:events:519:28)
    at IncomingMessage._destroy (node:_http_incoming:221:10)
    at _destroy (node:internal/streams/destroy:121:10)
    at IncomingMessage.destroy (node:internal/streams/destroy:83:5)
    at abortIncoming (node:_http_server:796:9)
    at socketOnClose (node:_http_server:790:3)
    at Socket.emit (node:events:531:35)
    at TCP.<anonymous> (node:net:339:12)
[Nest] 50  - 12/08/2024, 12:39:17 AM   ERROR [ExceptionsHandler] request aborted
BadRequestError: request aborted
    at IncomingMessage.onAborted (/opt/app/backend/node_modules/raw-body/index.js:245:10)
    at IncomingMessage.emit (node:events:519:28)
    at IncomingMessage._destroy (node:_http_incoming:221:10)
    at _destroy (node:internal/streams/destroy:121:10)
    at IncomingMessage.destroy (node:internal/streams/destroy:83:5)
    at abortIncoming (node:_http_server:796:9)
    at socketOnClose (node:_http_server:790:3)
    at Socket.emit (node:events:531:35)
    at TCP.<anonymous> (node:net:339:12)
[Nest] 50  - 12/08/2024, 12:39:17 AM   ERROR [ExceptionsHandler] request aborted
BadRequestError: request aborted
    at IncomingMessage.onAborted (/opt/app/backend/node_modules/raw-body/index.js:245:10)
    at IncomingMessage.emit (node:events:519:28)
    at IncomingMessage._destroy (node:_http_incoming:221:10)
    at _destroy (node:internal/streams/destroy:121:10)
    at IncomingMessage.destroy (node:internal/streams/destroy:83:5)
    at abortIncoming (node:_http_server:796:9)
    at socketOnClose (node:_http_server:790:3)
    at Socket.emit (node:events:531:35)
    at TCP.<anonymous> (node:net:339:12)

**Comment by stonith404** [comment]
Could you provide more details about the issue? Does it occur only with a specific file, or does it happen with any file? 
If you upload four files, does the fourth one fail? Additionally, does the failure persist indefinitely, or does the retry after 10 seconds successfully upload the file?

**Comment by Destinyg133** [comment]
I tried uploading 20gb (8 files) to a friend. All files are .mkv
Just uploading folder or zip didnt matter (most of files get updated) last 3 seem to always fail with slight chance of one of them actually getting uploaded and last 2 failing indefinitely

I also tried uploading less files at the same time. Its really random if it will fail or not. But if it does it mostly will stay like that without retrying. Uploading file by file seems to work just fine.

**Comment by stonith404** [comment]
Thanks. Do you have any reverse proxy in front? If yes, please try it again with nothing in front. Additionally please try it on another network and on another device.

"request aborted" means that the client has aborted the request so the issue is probably client or reverse proxy related.

**Comment by stonith404** [comment]
This https://github.com/stonith404/pingvin-share/issues/647#issuecomment-2434789887 might help.
